# Source: knative-serving/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-11-27T17:45:21Z"
  deletionTimestamp: null
  name: 'knative-serving-0.19.14'
  namespace: knative-serving
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: jenkins-x-bot
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        accountReference:
          - id: jenkins-x-bot
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: added variables
      sha: 138b38219c262a2efd790a13bc5920bde46e3b1c
    - author:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        fix: better default configuration
      sha: a5721afe1f59c92a784e23d529fa515cf07fd064
  gitCloneUrl: https://github.com/jenkins-x-charts/knative-serving.git
  gitHttpUrl: https://github.com/jenkins-x-charts/knative-serving
  gitOwner: jenkins-x-charts
  gitRepository: knative-serving
  name: 'knative-serving'
  releaseNotesURL: https://github.com/jenkins-x-charts/knative-serving/releases/tag/v0.19.14
  version: v0.19.14
status: {}
