# Source: knative-serving/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-11-27T14:53:12Z"
  deletionTimestamp: null
  name: 'knative-serving-0.19.13'
  namespace: knative-serving
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: jenkins-x-bot
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        accountReference:
          - id: jenkins-x-bot
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: added variables
      sha: c5bb217019a495a226ad4815b69c02ed80fa6109
    - author:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        fix: support configuration of domain
      sha: 38b77afc6b7095f23f3d3c5c6064718db1cd4c2c
  gitCloneUrl: https://github.com/jenkins-x-charts/knative-serving.git
  gitHttpUrl: https://github.com/jenkins-x-charts/knative-serving
  gitOwner: jenkins-x-charts
  gitRepository: knative-serving
  name: 'knative-serving'
  releaseNotesURL: https://github.com/jenkins-x-charts/knative-serving/releases/tag/v0.19.13
  version: v0.19.13
status: {}
