apiVersion: jenkins.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  labels:
    env: dev
    team: jx
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: dev
  namespace: jx
spec:
  kind: Development
  label: Development
  namespace: jx
  previewGitInfo:
    user: {}
  promotionStrategy: Never
  source:
    ref: master
    url: https://github.com/jstrachan/jx-demo-terraform-dev.git
  teamSettings:
    appsRepository: http://chartmuseum.jenkins-x.io
    bootRequirements: |
      autoUpdate:
        enabled: false
        schedule: ""
      cluster:
        chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
        clusterName: jstrachan-tekton
        environmentGitOwner: todo
        gitKind: github
        gitName: github
        gitServer: https://github.com
        gke:
          projectNumber: "688875092189"
        project: jenkins-x-labs-bdd
        provider: gke
        registry: gcr.io
        zone: europe-west2-a
      environments:
      - key: dev
        owner: jstrachan
        repository: jx-demo-terraform-dev
      - key: staging
      - key: production
      ingress:
        domain: 34.105.200.93.nip.io
        externalDNS: false
        namespaceSubDomain: -jx.
        tls:
          email: ""
          enabled: false
          production: true
      pipelineUser:
        username: jstrachan
      repository: nexus
      secretStorage: gsm
      storage:
      - name: logs
        url: gs://logs-jstrachan-tekton-20699896b252
      - name: reports
        url: gs://reports-jstrachan-tekton-20699896b252
      - name: repository
        url: gs://repository-jstrachan-tekton-20699896b252
      vault: {}
      webhook: lighthouse
    defaultScheduler:
      apiVersion: jenkins.io/v1
      kind: Scheduler
      name: jx-meta-pipeline
    dockerRegistryOrg: jenkins-x-labs-bdd
    envOrganisation: todo
    gitServer: https://github.com
    kubeProvider: gke
    pipelineUserEmail: jenkins-x@googlegroups.com
    pipelineUsername: jstrachan
    promotionEngine: Prow
    prowConfig: Scheduler
    storageLocations:
      - bucketUrl: gs://logs-jstrachan-tekton-20699896b252
        classifier: logs
      - bucketUrl: gs://reports-jstrachan-tekton-20699896b252
        classifier: reports
  webHookEngine: Lighthouse
status: {}
