# Source: knative-quickstart/templates/helloworld-php-service.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-php
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  template:
    spec:
      containers:
        - image: gcr.io/jenkins-x-labs-bdd/helloworld-php:0.0.12@sha256:ffd837d3f3286b5313de7e599d263ad0585f69ff450fd1ef431d09a7036a8825
          env:
            - name: TARGET
              value: "PHP Sample v1"
