# Source: knative-quickstart/templates/helloworld-nodejs-service.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-nodejs
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  template:
    spec:
      containers:
        - image: gcr.io/jenkins-x-labs-bdd/helloworld-nodejs:0.0.12@sha256:5ffc284831e1093cc7ea02ef9a3c196bb638da750e56a9b565f40333c5bc82de
          env:
            - name: TARGET
              value: "Node.js Sample v1"
