# Source: knative-quickstart/templates/helloworld-php-service.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-php
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  template:
    spec:
      containers:
        - image: gcr.io/jenkins-x-labs-bdd/helloworld-php:0.0.11@sha256:46b078ab2df794aaa3bd6f99ab497f9a36a936b72e405403eeca5a9485fc3409
          env:
            - name: TARGET
              value: "PHP Sample v1"
