# Source: knative-quickstart/templates/helloworld-go-service.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  template:
    spec:
      containers:
        - image: gcr.io/jenkins-x-labs-bdd/helloworld-go:0.0.10@sha256:0b291794cb29d2ee356465e1b69ac4f9168f3dd0df79f083d4da265e085fd83f
          env:
            - name: TARGET
              value: "Go Sample v1"
