# Source: knative-quickstart/templates/helloworld-nodejs-service.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-nodejs
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  template:
    spec:
      containers:
        - image: gcr.io/jenkins-x-labs-bdd/helloworld-nodejs:0.0.8@sha256:905506658fe5a8ad39654652273f184b6ff963a19088348bedf526b2fabe0781
          env:
            - name: TARGET
              value: "Node.js Sample v1"
