# Source: bdd-gh-1603125314/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-10-19T16:43:37Z"
  deletionTimestamp: null
  name: 'bdd-gh-1603125314-0.0.1'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      branch: master
      committer:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      message: |
        release 0.0.1
      sha: 9417ae4b4f84f670e2405db18d8fa9867997223a
    - author:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      branch: master
      committer:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      message: |
        Jenkins X build pack
      sha: 6003db1860f1ad1ccf82c2b07c02df502f43005a
  gitCloneUrl: https://github.com/cb-kubecd/bdd-gh-1603125314.git
  gitHttpUrl: https://github.com/cb-kubecd/bdd-gh-1603125314
  gitOwner: cb-kubecd
  gitRepository: bdd-gh-1603125314
  name: 'bdd-gh-1603125314'
  releaseNotesURL: https://github.com/cb-kubecd/bdd-gh-1603125314/releases/tag/v0.0.1
  version: v0.0.1
status: {}
