apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: jstrachan-tekton
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "688875092189"
    project: jenkins-x-labs-bdd
    provider: gke
    registry: gcr.io
    zone: europe-west2-a
  environments:
  - ingress:
      domain: ""
      externalDNS: false
      namespaceSubDomain: ""
      tls:
        email: ""
        enabled: false
        production: false
    key: dev
    owner: jstrachan
    repository: jx-demo-terraform-dev
  - ingress:
      domain: ""
      externalDNS: false
      namespaceSubDomain: ""
      tls:
        email: ""
        enabled: false
        production: false
    key: staging
  - ingress:
      domain: ""
      externalDNS: false
      namespaceSubDomain: ""
      tls:
        email: ""
        enabled: false
        production: false
    key: production
  ingress:
    domain: 35.184.150.204.nip.io
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  pipelineUser:
    username: jstrachan
  repository: nexus
  secretStorage: gsm
  storage:
  - name: logs
    url: gs://logs-jstrachan-tekton-20699896b252
  - name: reports
    url: gs://reports-jstrachan-tekton-20699896b252
  - name: repository
    url: gs://repository-jstrachan-tekton-20699896b252
  vault: {}
  webhook: lighthouse
