jxRequirements:
  autoUpdate:
    enabled: false
    schedule: ""
  bootConfigURL: https://github.com/jenkins-x/jx3-boot-config
  buildPacks:
    buildPackLibrary:
      gitRef: mink
      gitURL: https://github.com/jstrachan/jx3-pipeline-catalog.git
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: jstrachan-tekton
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "688875092189"
    namespace: jx
    project: jenkins-x-labs-bdd
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - ingress:
      domain: ""
      externalDNS: false
      namespaceSubDomain: ""
      tls:
        email: ""
        enabled: false
        production: false
    key: dev
    owner: jstrachan
    repository: jx-demo-terraform-dev
  - ingress:
      domain: ""
      externalDNS: false
      namespaceSubDomain: ""
      tls:
        email: ""
        enabled: false
        production: false
    key: staging
  - ingress:
      domain: ""
      externalDNS: false
      namespaceSubDomain: ""
      tls:
        email: ""
        enabled: false
        production: false
    key: production
  gitops: true
  ingress:
    domain: 35.184.150.204.nip.io
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  kaniko: true
  pipelineUser:
    username: jstrachan
  repository: nexus
  secretStorage: gsm
  storage:
    backup:
      enabled: false
      url: ""
    logs:
      enabled: true
      url: gs://logs-jstrachan-tekton-20699896b252
    reports:
      enabled: true
      url: gs://reports-jstrachan-tekton-20699896b252
    repository:
      enabled: true
      url: gs://repository-jstrachan-tekton-20699896b252
  vault: {}
  velero:
    schedule: ""
    ttl: ""
  versionStream:
    ref: master
    url: https://github.com/jenkins-x/jxr-versions.git
  webhook: lighthouse
jxRequirementsIngressExternalDNS:
  enabled: false
jxRequirementsIngressTLS:
  enabled: false
jxRequirementsVault:
  enabled: false
