apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-11-11T14:13:33Z"
  generateName: jx-boot-e6692c40-71ac-40bd-b738-4d24db840f63-
  labels:
    app: jx-boot
    controller-uid: 49435bf5-27f5-42ca-ad32-896b918e78fc
    jenkins-x.io/kind: jx-git-operator
    job-name: jx-boot-e6692c40-71ac-40bd-b738-4d24db840f63
  name: jx-boot-e6692c40-71ac-40bd-b738-4d24db840f63-sjcpl
  namespace: jx-git-operator
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: jx-boot-e6692c40-71ac-40bd-b738-4d24db840f63
    uid: 49435bf5-27f5-42ca-ad32-896b918e78fc
  resourceVersion: "27441002"
  selfLink: /api/v1/namespaces/jx-git-operator/pods/jx-boot-e6692c40-71ac-40bd-b738-4d24db840f63-sjcpl
  uid: 86b28d34-42a4-488b-af14-bd2d2923d95d
spec:
  containers:
  - args:
    - apply
    command:
    - make
    image: gcr.io/jenkinsxio/jx-cli:3.0.668
    imagePullPolicy: Always
    name: job
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /workspace
      name: workspace-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: jx-boot-job-token-hdr72
      readOnly: true
    workingDir: /workspace/source
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - args:
    - -c
    - 'mkdir -p $HOME; git config --global --add user.name $GIT_AUTHOR_NAME; git config --global --add user.email $GIT_AUTHOR_EMAIL; git config --global credential.helper store; git clone https://${GIT_USER}:${GIT_TOKEN}@${GIT_URL#"https://"} ${GIT_SUB_DIR}; echo cloned url: $(inputs.params.url) to dir: ${GIT_SUB_DIR}; cd ${GIT_SUB_DIR}; git checkout ${GIT_REVISION}; echo checked out revision: ${GIT_REVISION} to dir: ${GIT_SUB_DIR}'
    command:
    - /bin/sh
    env:
    - name: GIT_URL
      valueFrom:
        secretKeyRef:
          key: url
          name: jx-boot
    - name: GIT_USER
      valueFrom:
        secretKeyRef:
          key: username
          name: jx-boot
    - name: GIT_TOKEN
      valueFrom:
        secretKeyRef:
          key: password
          name: jx-boot
    - name: GIT_REVISION
      value: master
    - name: GIT_SUB_DIR
      value: source
    - name: GIT_AUTHOR_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_AUTHOR_NAME
      value: jenkins-x-labs-bot
    - name: GIT_COMMITTER_EMAIL
      value: jenkins-x@googlegroups.com
    - name: GIT_COMMITTER_NAME
      value: jenkins-x-labs-bot
    - name: XDG_CONFIG_HOME
      value: /workspace/xdg_config
    image: gcr.io/jenkinsxio/jx-cli:3.0.668
    imagePullPolicy: IfNotPresent
    name: git-clone
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /workspace
      name: workspace-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: jx-boot-job-token-hdr72
      readOnly: true
    workingDir: /workspace
  nodeName: gke-jstrachan-tekton-default-pool-154aeb80-n21q
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: jx-boot-job
  serviceAccountName: jx-boot-job
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: workspace-volume
  - name: jx-boot-job-token-hdr72
    secret:
      defaultMode: 420
      secretName: jx-boot-job-token-hdr72
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:13:41Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:15:23Z"
    message: 'containers with unready status: [job]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:15:23Z"
    message: 'containers with unready status: [job]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:13:33Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://9b8bfdf757eaa97f32c0fd8dfd3c385bf5ddd1c4554276a76d36a9b320333ab8
    image: gcr.io/jenkinsxio/jx-cli:3.0.668
    imageID: docker-pullable://gcr.io/jenkinsxio/jx-cli@sha256:ce47e63336a9cb1138b5fc5d2c1bfec92e35845074e6a2e24d5f958a17e3d354
    lastState: {}
    name: job
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://9b8bfdf757eaa97f32c0fd8dfd3c385bf5ddd1c4554276a76d36a9b320333ab8
        exitCode: 2
        finishedAt: "2020-11-11T14:15:23Z"
        reason: Error
        startedAt: "2020-11-11T14:13:41Z"
  hostIP: 10.128.0.5
  initContainerStatuses:
  - containerID: docker://11f12002dfe3d0265b4067d7531fe59dff578b505e738fbbacce8f80f6f7a05e
    image: gcr.io/jenkinsxio/jx-cli:3.0.668
    imageID: docker-pullable://gcr.io/jenkinsxio/jx-cli@sha256:ce47e63336a9cb1138b5fc5d2c1bfec92e35845074e6a2e24d5f958a17e3d354
    lastState: {}
    name: git-clone
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://11f12002dfe3d0265b4067d7531fe59dff578b505e738fbbacce8f80f6f7a05e
        exitCode: 0
        finishedAt: "2020-11-11T14:13:40Z"
        reason: Completed
        startedAt: "2020-11-11T14:13:35Z"
  phase: Failed
  podIP: 10.8.5.241
  podIPs:
  - ip: 10.8.5.241
  qosClass: BestEffort
  startTime: "2020-11-11T14:13:33Z"
