apiVersion: v1
kind: Pod
metadata:
  annotations:
    comcast.github.io/check-name: jx-install
  creationTimestamp: "2020-11-11T13:54:17Z"
  labels:
    app: kuberhealthy-check
    kuberhealthy-check-name: jx-install
    kuberhealthy-run-id: bbe4b1be-d3d9-4e6c-88ab-2fdc900e7ebc
  name: jx-install-1605102851
  namespace: jx-git-operator
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: kuberhealthy-5c46966647-6db64
    uid: d98a024b-7504-4cdd-a3bb-c70c6128d8fb
  resourceVersion: "27428435"
  selfLink: /api/v1/namespaces/jx-git-operator/pods/jx-install-1605102851
  uid: b4642cf4-2365-48ee-a2a7-cb86664f5ddb
spec:
  containers:
  - env:
    - name: KH_REPORTING_URL
      value: http://kuberhealthy.kuberhealthy.svc.cluster.local/externalCheckStatus
    - name: KH_RUN_UUID
      value: bbe4b1be-d3d9-4e6c-88ab-2fdc900e7ebc
    - name: KH_CHECK_RUN_DEADLINE
      value: "1605102972"
    - name: KH_POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: gcr.io/jenkinsxio/jx-install:0.0.51
    imagePullPolicy: IfNotPresent
    name: jx-install
    resources:
      limits:
        cpu: 40m
      requests:
        cpu: 25m
        memory: 15Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: jx-install-sa-token-kz8w4
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-jstrachan-tekton-default-pool-154aeb80-pmxj
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: jx-install-sa
  serviceAccountName: jx-install-sa
  terminationGracePeriodSeconds: 60
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: jx-install-sa-token-kz8w4
    secret:
      defaultMode: 420
      secretName: jx-install-sa-token-kz8w4
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:54:17Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:54:22Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:54:22Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:54:17Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://357323182e4876e29da89b8eb8d45f1fd97d107f4fbd62c6959ec39cf7fe5e15
    image: gcr.io/jenkinsxio/jx-install:0.0.51
    imageID: docker-pullable://gcr.io/jenkinsxio/jx-install@sha256:bfb477d82a44122ecd03c45438ea3babe8bfeb883d4f67bf5f2407e40a5314a1
    lastState: {}
    name: jx-install
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://357323182e4876e29da89b8eb8d45f1fd97d107f4fbd62c6959ec39cf7fe5e15
        exitCode: 0
        finishedAt: "2020-11-11T13:54:22Z"
        reason: Completed
        startedAt: "2020-11-11T13:54:20Z"
  hostIP: 10.128.0.11
  phase: Succeeded
  podIP: 10.8.7.3
  podIPs:
  - ip: 10.8.7.3
  qosClass: Burstable
  startTime: "2020-11-11T13:54:17Z"
