# Source: nodey534/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-10-20T12:03:52Z"
  deletionTimestamp: null
  name: 'nodey534-1.0.6'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      branch: master
      committer:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      message: |
        release 1.0.6
      sha: f64e2fd2d4dcb3bd3e852f18f4dead247a3912dd
    - author:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      branch: master
      committer:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      message: |
        release 1.0.6
      sha: d2f169d81138e7553adc67622236f5ba5d4eecb0
    - author:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        accountReference:
          - id: github-0
            provider: jenkins.io/git-github-userid
        email: noreply@github.com
        name: GitHub
      message: Update index.html
      sha: 6656ae9e46c12d3eade2c8dd8298b60c23c7d6e4
    - author:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        accountReference:
          - id: github-0
            provider: jenkins.io/git-github-userid
        email: noreply@github.com
        name: GitHub
      message: 'fix: add default env vars'
      sha: ee412447a6fb7ad08c72c6a142e4b97c2a092260
  gitCloneUrl: https://github.com/jstrachan/nodey534.git
  gitHttpUrl: https://github.com/jstrachan/nodey534
  gitOwner: jstrachan
  gitRepository: nodey534
  name: 'nodey534'
  releaseNotesURL: https://github.com/jstrachan/nodey534/releases/tag/v1.0.6
  version: v1.0.6
status: {}
