# Source: nodey534/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-10-13T08:32:55Z"
  deletionTimestamp: null
  name: 'nodey534-1.0.1'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      branch: master
      committer:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      message: |
        release 1.0.1
      sha: ad9b39ddaab1c6e5e4d37e2fab40bde79f494856
    - author:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      branch: master
      committer:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      message: |
        release 1.0.1
      sha: 35c169cb11e31ab7a7f1d0550794e4bd1f8c6934
    - author:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        accountReference:
          - provider: jenkins.io/git-github-userid
        email: noreply@github.com
        name: GitHub
      message: Update index.html
      sha: 93f560ed0f78ec95a7c1c31f67bb0cb303ff356f
  gitCloneUrl: https://github.com/jstrachan/nodey534.git
  gitHttpUrl: https://github.com/jstrachan/nodey534
  gitOwner: jstrachan
  gitRepository: nodey534
  name: 'nodey534'
  releaseNotesURL: https://github.com/jstrachan/nodey534/releases/tag/v1.0.1
  version: v1.0.1
status: {}
