# Source: knative-net-istio/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-12-02T12:37:24Z"
  deletionTimestamp: null
  name: 'knative-net-istio-0.19.19'
  namespace: knative-serving
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: jenkins-x-bot
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        accountReference:
          - id: jenkins-x-bot
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: added variables
      sha: c6673010c045ce2a0197d4b01ba28c066954da4d
    - author:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        fix: release
      sha: 1e226702d859d41e626dbb861f08b214a17e7817
  gitCloneUrl: https://github.com/jenkins-x-charts/knative-serving.git
  gitHttpUrl: https://github.com/jenkins-x-charts/knative-serving
  gitOwner: jenkins-x-charts
  gitRepository: knative-serving
  name: 'knative-net-istio'
  releaseNotesURL: https://github.com/jenkins-x-charts/knative-serving/releases/tag/v0.19.19
  version: v0.19.19
status: {}
