# Source: knative-net-istio/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-12-02T14:09:36Z"
  deletionTimestamp: null
  name: 'knative-net-istio-0.19.21'
  namespace: knative-serving
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: jenkins-x-bot
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        accountReference:
          - id: jenkins-x-bot
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: added variables
      sha: 717c93b1a9d7b9e4802aedc1d7ae1d723ba67982
    - author:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        fix: add optional local domain value in the helm chart
      sha: 916f356f862fdefac5a619acb6cf54526955ec16
  gitCloneUrl: https://github.com/jenkins-x-charts/knative-serving.git
  gitHttpUrl: https://github.com/jenkins-x-charts/knative-serving
  gitOwner: jenkins-x-charts
  gitRepository: knative-serving
  name: 'knative-net-istio'
  releaseNotesURL: https://github.com/jenkins-x-charts/knative-serving/releases/tag/v0.19.21
  version: v0.19.21
status: {}
