# Source: jx-preview/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-11-18T07:53:03Z"
  deletionTimestamp: null
  name: 'jx-preview-0.0.122'
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        fix: improve image to avoid downloading plugin each time
      sha: 54310ca970bd0232ecb5cf1c454aa3301a0b6ceb
    - author:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        fix: better preview
      sha: 688f30efc34f90b0167ca08ab850646c4cdb71ba
  gitCloneUrl: https://github.com/jenkins-x/jx-preview.git
  gitHttpUrl: https://github.com/jenkins-x/jx-preview
  gitOwner: jenkins-x
  gitRepository: jx-preview
  name: 'jx-preview'
  version: 0.0.122
status: {}
