# Source: bdd-gh-1602869144/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-10-16T17:31:40Z"
  deletionTimestamp: null
  name: 'bdd-gh-1602869144-0.0.1'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      branch: master
      committer:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      message: |
        release 0.0.1
      sha: 8ec0c37cbeedb3c2fecb87d8790f98e5aa73e321
    - author:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      branch: master
      committer:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      message: |
        Jenkins X build pack
      sha: b4e3b3ba95c03949a002ce67f699f4066d0e36e5
  gitCloneUrl: https://github.com/cb-kubecd/bdd-gh-1602869144.git
  gitHttpUrl: https://github.com/cb-kubecd/bdd-gh-1602869144
  gitOwner: cb-kubecd
  gitRepository: bdd-gh-1602869144
  name: 'bdd-gh-1602869144'
  releaseNotesURL: https://github.com/cb-kubecd/bdd-gh-1602869144/releases/tag/v0.0.1
  version: v0.0.1
status: {}
