apiVersion: v1
kind: Pod
metadata:
  annotations:
    components.gke.io/component-name: event-exporter
    components.gke.io/component-version: 1.0.8
  creationTimestamp: "2020-11-11T14:42:31Z"
  generateName: event-exporter-gke-77cccd97c6-
  labels:
    k8s-app: event-exporter
    pod-template-hash: 77cccd97c6
    version: v0.3.4
  name: event-exporter-gke-77cccd97c6-6j7jr
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: event-exporter-gke-77cccd97c6
    uid: 363e6f64-a6cc-40db-99d5-47208191b06f
  resourceVersion: "27455027"
  selfLink: /api/v1/namespaces/kube-system/pods/event-exporter-gke-77cccd97c6-6j7jr
  uid: 411fffa5-7eb5-47e9-a763-b1ed5047e666
spec:
  containers:
  - command:
    - /event-exporter
    - -sink-opts=-stackdriver-resource-model=new -endpoint=https://logging.googleapis.com
    image: gke.gcr.io/event-exporter:v0.3.4-gke.0
    imagePullPolicy: IfNotPresent
    name: event-exporter
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: event-exporter-sa-token-lwfc2
      readOnly: true
  - command:
    - /monitor
    - --stackdriver-prefix=container.googleapis.com/internal/addons
    - --api-override=https://monitoring.googleapis.com/
    - --source=event_exporter:http://localhost:80?whitelisted=stackdriver_sink_received_entry_count,stackdriver_sink_request_count,stackdriver_sink_successfully_sent_entry_count
    - --pod-id=$(POD_NAME)
    - --namespace-id=$(POD_NAMESPACE)
    - --node-name=$(NODE_NAME)
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    image: gke.gcr.io/prometheus-to-sd:v0.10.0-gke.0
    imagePullPolicy: IfNotPresent
    name: prometheus-to-sd-exporter
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: event-exporter-sa-token-lwfc2
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-jstrachan-tekton-default-pool-154aeb80-pmxj
  nodeSelector:
    kubernetes.io/os: linux
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: event-exporter-sa
  serviceAccountName: event-exporter-sa
  terminationGracePeriodSeconds: 120
  tolerations:
  - key: components.gke.io/gke-managed-components
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: ""
    name: ssl-certs
  - name: event-exporter-sa-token-lwfc2
    secret:
      defaultMode: 420
      secretName: event-exporter-sa-token-lwfc2
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:42:31Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:43:13Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:43:13Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:42:31Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://14674b4295095e22564099a08c446e102114be3e5e19def68fdbc9bf5aaa6f29
    image: gke.gcr.io/event-exporter:v0.3.4-gke.0
    imageID: docker-pullable://gke.gcr.io/event-exporter@sha256:34b034af960047020f4674151bbb2b55878f82a0b76dabca81b518e9fe82180d
    lastState: {}
    name: event-exporter
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-11-11T14:42:35Z"
  - containerID: docker://21afadcdd58ce711f3e6709aa546b2fe7c4e04f40aeeae269ece6f8b5b371b5d
    image: gke.gcr.io/prometheus-to-sd:v0.10.0-gke.0
    imageID: docker-pullable://gke.gcr.io/prometheus-to-sd@sha256:c5e12680a431990d5e39ed249dcb43a7672e99f7ef94a9928be40cf2f418f62f
    lastState: {}
    name: prometheus-to-sd-exporter
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-11-11T14:42:35Z"
  hostIP: 10.128.0.11
  phase: Running
  podIP: 10.8.7.160
  podIPs:
  - ip: 10.8.7.160
  qosClass: BestEffort
  startTime: "2020-11-11T14:42:31Z"
