apiVersion: v1
kind: Pod
metadata:
  annotations:
    components.gke.io/component-name: event-exporter
    components.gke.io/component-version: 1.0.7
  creationTimestamp: "2020-11-07T03:13:19Z"
  generateName: event-exporter-gke-8489df9489-
  labels:
    k8s-app: event-exporter
    pod-template-hash: 8489df9489
    version: v0.3.1
  name: event-exporter-gke-8489df9489-4nkwt
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: event-exporter-gke-8489df9489
    uid: 54b7a314-fe0e-458a-a8c3-526f37b4127f
  resourceVersion: "22547349"
  selfLink: /api/v1/namespaces/kube-system/pods/event-exporter-gke-8489df9489-4nkwt
  uid: b55e4b70-a3fd-456f-84cd-2e596a7438d8
spec:
  containers:
  - command:
    - /event-exporter
    - -sink-opts=-stackdriver-resource-model=new -endpoint=https://logging.googleapis.com
    image: gke.gcr.io/event-exporter:v0.3.3-gke.0
    imagePullPolicy: IfNotPresent
    name: event-exporter
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: event-exporter-sa-token-lwfc2
      readOnly: true
  - command:
    - /monitor
    - --stackdriver-prefix=container.googleapis.com/internal/addons
    - --api-override=https://monitoring.googleapis.com/
    - --source=event_exporter:http://localhost:80?whitelisted=stackdriver_sink_received_entry_count,stackdriver_sink_request_count,stackdriver_sink_successfully_sent_entry_count
    - --pod-id=$(POD_NAME)
    - --namespace-id=$(POD_NAMESPACE)
    - --node-name=$(NODE_NAME)
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    image: gke.gcr.io/prometheus-to-sd:v0.10.0-gke.0
    imagePullPolicy: IfNotPresent
    name: prometheus-to-sd-exporter
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: event-exporter-sa-token-lwfc2
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-jstrachan-tekton-default-pool-154aeb80-pmxj
  nodeSelector:
    kubernetes.io/os: linux
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: event-exporter-sa
  serviceAccountName: event-exporter-sa
  terminationGracePeriodSeconds: 120
  tolerations:
  - key: components.gke.io/gke-managed-components
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: ""
    name: ssl-certs
  - name: event-exporter-sa-token-lwfc2
    secret:
      defaultMode: 420
      secretName: event-exporter-sa-token-lwfc2
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-07T03:13:19Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-07T03:14:58Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-07T03:14:58Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-07T03:13:19Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://cf8a978086a9088f12435feee1899016e34402aeaf55f21d0266cc9fcf4fdf01
    image: gke.gcr.io/event-exporter:v0.3.3-gke.0
    imageID: docker-pullable://gke.gcr.io/event-exporter@sha256:6c08dc79478246a7cf9b7f7242dbc6ab0fdde2610b346db06faac69ec548d4f2
    lastState: {}
    name: event-exporter
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-11-07T03:14:13Z"
  - containerID: docker://ccca0c8372eccd4311fc1e8893fbcf2cc2863951315d00261dd9c9686511bb4a
    image: gke.gcr.io/prometheus-to-sd:v0.10.0-gke.0
    imageID: docker-pullable://gke.gcr.io/prometheus-to-sd@sha256:c5e12680a431990d5e39ed249dcb43a7672e99f7ef94a9928be40cf2f418f62f
    lastState: {}
    name: prometheus-to-sd-exporter
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-11-07T03:14:14Z"
  hostIP: 10.128.0.11
  phase: Running
  podIP: 10.8.7.5
  podIPs:
  - ip: 10.8.7.5
  qosClass: BestEffort
  startTime: "2020-11-07T03:13:19Z"
