apiVersion: v1
kind: Pod
metadata:
  annotations:
    EnableNodeJournal: "false"
    EnablePodSecurityPolicy: "false"
    SystemOnlyLogging: "false"
    components.gke.io/component-name: fluentbit
    components.gke.io/component-version: 1.3.0
    monitoring.gke.io/path: /api/v1/metrics/prometheus
  creationTimestamp: "2020-11-11T14:42:37Z"
  generateName: fluentbit-gke-
  labels:
    component: fluentbit-gke
    controller-revision-hash: 5979845fff
    k8s-app: fluentbit-gke
    kubernetes.io/cluster-service: "true"
    pod-template-generation: "1"
  name: fluentbit-gke-dbnfx
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: fluentbit-gke
    uid: a75ea8eb-5070-4d56-8c3e-573661681865
  resourceVersion: "27455517"
  selfLink: /api/v1/namespaces/kube-system/pods/fluentbit-gke-dbnfx
  uid: d0e3761c-ad78-4f22-a819-65963a51dac2
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - gke-jstrachan-tekton-default-pool-154aeb80-pmxj
  containers:
  - image: gke.gcr.io/fluent-bit:v1.3.11-gke.0
    imagePullPolicy: IfNotPresent
    name: fluentbit
    ports:
    - containerPort: 2020
      hostPort: 2020
      name: metrics
      protocol: TCP
    resources:
      limits:
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 100Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/google-fluentbit/pos-files
      name: varrun
    - mountPath: /var/log
      name: varlog
    - mountPath: /var/lib/kubelet/pods
      name: varlibkubeletpods
    - mountPath: /var/lib/docker/containers
      name: varlibdockercontainers
      readOnly: true
    - mountPath: /fluent-bit/etc/
      name: config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: fluentbit-gke-token-j5q2w
      readOnly: true
  - command:
    - /fluent-bit-gke-exporter
    - --kubernetes-separator=_
    - --stackdriver-resource-model=k8s
    - --enable-pod-label-discovery
    - --pod-label-dot-replacement=_
    - --split-stdout-stderr
    - --logtostderr
    image: gke.gcr.io/fluent-bit-gke-exporter:v0.11.0-gke.0
    imagePullPolicy: IfNotPresent
    name: fluentbit-gke
    ports:
    - containerPort: 2021
      hostPort: 2021
      name: metrics
      protocol: TCP
    resources:
      limits:
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 100Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: fluentbit-gke-token-j5q2w
      readOnly: true
  dnsPolicy: Default
  enableServiceLinks: true
  hostNetwork: true
  nodeName: gke-jstrachan-tekton-default-pool-154aeb80-pmxj
  nodeSelector:
    beta.kubernetes.io/os: linux
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: fluentbit-gke
  serviceAccountName: fluentbit-gke
  terminationGracePeriodSeconds: 120
  tolerations:
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists
  - key: components.gke.io/gke-managed-components
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    operator: Exists
  volumes:
  - hostPath:
      path: /var/run/google-fluentbit/pos-files
      type: ""
    name: varrun
  - hostPath:
      path: /var/log
      type: ""
    name: varlog
  - hostPath:
      path: /var/lib/kubelet/pods
      type: ""
    name: varlibkubeletpods
  - hostPath:
      path: /var/lib/docker/containers
      type: ""
    name: varlibdockercontainers
  - configMap:
      defaultMode: 420
      name: fluentbit-gke-config-v1.0.4
    name: config-volume
  - name: fluentbit-gke-token-j5q2w
    secret:
      defaultMode: 420
      secretName: fluentbit-gke-token-j5q2w
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:42:38Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:43:53Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:43:53Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:42:38Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://4be01ed524397ba78d4ef20dc12963dcea8bf6e5036ca96ad093dbe342bc8ae4
    image: gke.gcr.io/fluent-bit:v1.3.11-gke.0
    imageID: docker-pullable://gke.gcr.io/fluent-bit@sha256:fb78c311517093a2887151d2e535aec38b82fdfbf0bbe7bdf393433ca2c534a3
    lastState: {}
    name: fluentbit
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-11-11T14:42:45Z"
  - containerID: docker://e109b30158a74a34af0c857472b193c2a1151954fdbe12a3047ce37131e81ce3
    image: gke.gcr.io/fluent-bit-gke-exporter:v0.11.0-gke.0
    imageID: docker-pullable://gke.gcr.io/fluent-bit-gke-exporter@sha256:5452f6e519097802b317ea5d65107aa180f2e33fc43cc28ad4e983a768892d6d
    lastState: {}
    name: fluentbit-gke
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-11-11T14:42:47Z"
  hostIP: 10.128.0.11
  phase: Running
  podIP: 10.128.0.11
  podIPs:
  - ip: 10.128.0.11
  qosClass: Burstable
  startTime: "2020-11-11T14:42:38Z"
