apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/config.hash: 1b13071a0b296453ef7a32701441f230
    kubernetes.io/config.mirror: 1b13071a0b296453ef7a32701441f230
    kubernetes.io/config.seen: "2020-11-07T03:22:37.575935576Z"
    kubernetes.io/config.source: file
  creationTimestamp: "2020-11-07T03:22:38Z"
  labels:
    component: kube-proxy
    tier: node
  name: kube-proxy-gke-jstrachan-tekton-nap-n1-standard--0a7ecf20-446q
  namespace: kube-system
  resourceVersion: "22553374"
  selfLink: /api/v1/namespaces/kube-system/pods/kube-proxy-gke-jstrachan-tekton-nap-n1-standard--0a7ecf20-446q
  uid: 9bb5918d-8f72-4e75-adce-762f74f710c1
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - exec kube-proxy --master=https://35.238.250.202 --kubeconfig=/var/lib/kube-proxy/kubeconfig --cluster-cidr=10.8.0.0/14 --oom-score-adj=-998 --v=2 --feature-gates=DynamicKubeletConfig=false,TaintBasedEvictions=false,RotateKubeletServerCertificate=true --iptables-sync-period=1m --iptables-min-sync-period=10s --ipvs-sync-period=1m --ipvs-min-sync-period=10s 1>>/var/log/kube-proxy.log 2>&1
    image: gke.gcr.io/kube-proxy-amd64:v1.16.13-gke.401
    imagePullPolicy: IfNotPresent
    name: kube-proxy
    resources:
      requests:
        cpu: 100m
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: etc-ssl-certs
      readOnly: true
    - mountPath: /usr/share/ca-certificates
      name: usr-ca-certs
      readOnly: true
    - mountPath: /var/log
      name: varlog
    - mountPath: /var/lib/kube-proxy/kubeconfig
      name: kubeconfig
    - mountPath: /run/xtables.lock
      name: iptableslock
    - mountPath: /lib/modules
      name: lib-modules
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: gke-jstrachan-tekton-nap-n1-standard--0a7ecf20-446q
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists
  volumes:
  - hostPath:
      path: /usr/share/ca-certificates
      type: ""
    name: usr-ca-certs
  - hostPath:
      path: /etc/ssl/certs
      type: ""
    name: etc-ssl-certs
  - hostPath:
      path: /var/lib/kube-proxy/kubeconfig
      type: FileOrCreate
    name: kubeconfig
  - hostPath:
      path: /var/log
      type: ""
    name: varlog
  - hostPath:
      path: /run/xtables.lock
      type: FileOrCreate
    name: iptableslock
  - hostPath:
      path: /lib/modules
      type: ""
    name: lib-modules
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-07T03:22:38Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-07T03:22:41Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-07T03:22:41Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-07T03:22:38Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://947f83b02ac803df9d14ecb1d454feb9c3aab00dcbf17840c89f5eded9adb5be
    image: gke.gcr.io/kube-proxy-amd64:v1.16.13-gke.401
    imageID: docker://sha256:89825752aba466019f1014c4b3dc0e3000b37b0ad6da689624db44c88da3f30c
    lastState: {}
    name: kube-proxy
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-11-07T03:22:39Z"
  hostIP: 10.128.0.14
  phase: Running
  podIP: 10.128.0.14
  podIPs:
  - ip: 10.128.0.14
  qosClass: Burstable
  startTime: "2020-11-07T03:22:38Z"
