apiVersion: v1
kind: Pod
metadata:
  annotations:
    components.gke.io/component-name: kubedns
    components.gke.io/component-version: 1.0.5
    scheduler.alpha.kubernetes.io/critical-pod: ""
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2020-11-11T14:42:35Z"
  generateName: kube-dns-7bb4975665-
  labels:
    k8s-app: kube-dns
    pod-template-hash: 7bb4975665
  name: kube-dns-7bb4975665-9wq57
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: kube-dns-7bb4975665
    uid: ac5f08cd-8cfb-4999-bf63-583447bf20b4
  resourceVersion: "27455263"
  selfLink: /api/v1/namespaces/kube-system/pods/kube-dns-7bb4975665-9wq57
  uid: 31d901d1-5506-4132-af84-56b94de86d6d
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: k8s-app
              operator: In
              values:
              - kube-dns
          topologyKey: kubernetes.io/hostname
        weight: 100
  containers:
  - args:
    - --domain=cluster.local.
    - --dns-port=10053
    - --config-dir=/kube-dns-config
    - --v=2
    env:
    - name: PROMETHEUS_PORT
      value: "10055"
    image: gke.gcr.io/k8s-dns-kube-dns-amd64:1.15.16-gke.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /healthcheck/kubedns
        port: 10054
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: kubedns
    ports:
    - containerPort: 10053
      name: dns-local
      protocol: UDP
    - containerPort: 10053
      name: dns-tcp-local
      protocol: TCP
    - containerPort: 10055
      name: metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /readiness
        port: 8081
        scheme: HTTP
      initialDelaySeconds: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        memory: 210Mi
      requests:
        cpu: 100m
        memory: 70Mi
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsGroup: 1001
      runAsUser: 1001
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /kube-dns-config
      name: kube-dns-config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-dns-token-gvk7l
      readOnly: true
  - args:
    - -v=2
    - -logtostderr
    - -configDir=/etc/k8s/dns/dnsmasq-nanny
    - -restartDnsmasq=true
    - --
    - -k
    - --cache-size=1000
    - --no-negcache
    - --dns-forward-max=1500
    - --log-facility=-
    - --server=/cluster.local/127.0.0.1#10053
    - --server=/in-addr.arpa/127.0.0.1#10053
    - --server=/ip6.arpa/127.0.0.1#10053
    image: gke.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.15.16-gke.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /healthcheck/dnsmasq
        port: 10054
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: dnsmasq
    ports:
    - containerPort: 53
      name: dns
      protocol: UDP
    - containerPort: 53
      name: dns-tcp
      protocol: TCP
    resources:
      requests:
        cpu: 150m
        memory: 20Mi
    securityContext:
      capabilities:
        add:
        - NET_BIND_SERVICE
        - SETGID
        drop:
        - all
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/k8s/dns/dnsmasq-nanny
      name: kube-dns-config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-dns-token-gvk7l
      readOnly: true
  - args:
    - --v=2
    - --logtostderr
    - --probe=kubedns,127.0.0.1:10053,kubernetes.default.svc.cluster.local,5,SRV
    - --probe=dnsmasq,127.0.0.1:53,kubernetes.default.svc.cluster.local,5,SRV
    image: gke.gcr.io/k8s-dns-sidecar-amd64:1.15.16-gke.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /metrics
        port: 10054
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: sidecar
    ports:
    - containerPort: 10054
      name: metrics
      protocol: TCP
    resources:
      requests:
        cpu: 10m
        memory: 20Mi
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsGroup: 1001
      runAsUser: 1001
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-dns-token-gvk7l
      readOnly: true
  - command:
    - /monitor
    - --source=kubedns:http://localhost:10054?whitelisted=probe_kubedns_latency_ms,probe_kubedns_errors,dnsmasq_misses,dnsmasq_hits
    - --stackdriver-prefix=container.googleapis.com/internal/addons
    - --api-override=https://monitoring.googleapis.com/
    - --pod-id=$(POD_NAME)
    - --namespace-id=$(POD_NAMESPACE)
    - --v=2
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: gke.gcr.io/prometheus-to-sd:v0.4.2
    imagePullPolicy: IfNotPresent
    name: prometheus-to-sd
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsGroup: 1001
      runAsUser: 1001
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-dns-token-gvk7l
      readOnly: true
  dnsPolicy: Default
  enableServiceLinks: true
  nodeName: gke-jstrachan-tekton-default-pool-154aeb80-n21q
  nodeSelector:
    beta.kubernetes.io/os: linux
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 65534
    supplementalGroups:
    - 65534
  serviceAccount: kube-dns
  serviceAccountName: kube-dns
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - key: components.gke.io/gke-managed-components
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      name: kube-dns
      optional: true
    name: kube-dns-config
  - name: kube-dns-token-gvk7l
    secret:
      defaultMode: 420
      secretName: kube-dns-token-gvk7l
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:42:35Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:43:34Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:43:34Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:42:35Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://c4c0cd61b8802f3ba26160d9528acf06d24c039a6e4fdecd612ac62653205f8a
    image: gke.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.15.16-gke.0
    imageID: docker-pullable://gke.gcr.io/k8s-dns-dnsmasq-nanny-amd64@sha256:bd25b644c9e14dcfe77f54ec7f249b151850f6ad23548e02046aa9204fb11d25
    lastState: {}
    name: dnsmasq
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-11-11T14:42:48Z"
  - containerID: docker://7fb749ea9d18170d142db6b4b31657c743274be5115642319d80e87c2e93f759
    image: gke.gcr.io/k8s-dns-kube-dns-amd64:1.15.16-gke.0
    imageID: docker-pullable://gke.gcr.io/k8s-dns-kube-dns-amd64@sha256:9e76595f4bf8490bbaff6acfcc1f3243a4bb112481f7f59b3a52c2b09e6ced3c
    lastState: {}
    name: kubedns
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-11-11T14:42:41Z"
  - containerID: docker://5682722f130573362e89bdbe2481aa328d863ab7543a566074e4f4a23bb5cf19
    image: gke.gcr.io/prometheus-to-sd:v0.4.2
    imageID: docker-pullable://gke.gcr.io/prometheus-to-sd@sha256:aca8ef83a7fae83f1f8583e978dd4d1ff655b9f2ca0a76bda5edce6d8965bdf2
    lastState:
      terminated:
        containerID: docker://48cf39e1cd6a0f27c66e0378abf0afc0e5149a2dda2698e1eb95c2cff23987b7
        exitCode: 255
        finishedAt: "2020-11-11T14:43:09Z"
        reason: Error
        startedAt: "2020-11-11T14:43:09Z"
    name: prometheus-to-sd
    ready: true
    restartCount: 3
    started: true
    state:
      running:
        startedAt: "2020-11-11T14:43:34Z"
  - containerID: docker://fbcb674de46c0ef0be8817aafe2c88353848c073dc806293e881c163cc166361
    image: gke.gcr.io/k8s-dns-sidecar-amd64:1.15.16-gke.0
    imageID: docker-pullable://gke.gcr.io/k8s-dns-sidecar-amd64@sha256:f890a184d953ef2a80f756ff1ab93e92cc6cd76cdb0c89b56d1d30846d72249b
    lastState: {}
    name: sidecar
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-11-11T14:42:52Z"
  hostIP: 10.128.0.5
  phase: Running
  podIP: 10.8.5.245
  podIPs:
  - ip: 10.8.5.245
  qosClass: Burstable
  startTime: "2020-11-11T14:42:35Z"
