apiVersion: v1
kind: Pod
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: docker/default
  creationTimestamp: "2020-11-11T14:42:35Z"
  generateName: metrics-server-v0.3.6-547dc87f5f-
  labels:
    k8s-app: metrics-server
    pod-template-hash: 547dc87f5f
    version: v0.3.6
  name: metrics-server-v0.3.6-547dc87f5f-tn2vb
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: metrics-server-v0.3.6-547dc87f5f
    uid: 5213848c-6146-4d3c-8166-4240cf564a2e
  resourceVersion: "27454757"
  selfLink: /api/v1/namespaces/kube-system/pods/metrics-server-v0.3.6-547dc87f5f-tn2vb
  uid: 7fecbf1a-e24c-4fb7-8b7f-590bc7559653
spec:
  containers:
  - command:
    - /metrics-server
    - --metric-resolution=30s
    - --kubelet-port=10255
    - --deprecated-kubelet-completely-insecure=true
    - --kubelet-preferred-address-types=InternalIP,Hostname,InternalDNS,ExternalDNS,ExternalIP
    image: k8s.gcr.io/metrics-server-amd64:v0.3.6
    imagePullPolicy: IfNotPresent
    name: metrics-server
    ports:
    - containerPort: 443
      name: https
      protocol: TCP
    resources:
      limits:
        cpu: 43m
        memory: 55Mi
      requests:
        cpu: 43m
        memory: 55Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: metrics-server-token-hv8zf
      readOnly: true
  - command:
    - /pod_nanny
    - --config-dir=/etc/config
    - --cpu=40m
    - --extra-cpu=0.5m
    - --memory=35Mi
    - --extra-memory=4Mi
    - --threshold=5
    - --deployment=metrics-server-v0.3.6
    - --container=metrics-server
    - --poll-period=300000
    - --estimator=exponential
    - --scale-down-delay=24h
    - --minClusterSize=5
    env:
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: gke.gcr.io/addon-resizer:1.8.8-gke.1
    imagePullPolicy: IfNotPresent
    name: metrics-server-nanny
    resources:
      limits:
        cpu: 100m
        memory: 300Mi
      requests:
        cpu: 5m
        memory: 50Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/config
      name: metrics-server-config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: metrics-server-token-hv8zf
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-jstrachan-tekton-default-pool-154aeb80-n21q
  nodeSelector:
    kubernetes.io/os: linux
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: metrics-server
  serviceAccountName: metrics-server
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - key: components.gke.io/gke-managed-components
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      name: metrics-server-config
    name: metrics-server-config-volume
  - name: metrics-server-token-hv8zf
    secret:
      defaultMode: 420
      secretName: metrics-server-token-hv8zf
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:42:35Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:42:54Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:42:54Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:42:35Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://f3d96fc4ad4cc806af8c90d3a0626e688a53edb5d9b85382320384c4c4b71fab
    image: k8s.gcr.io/metrics-server-amd64:v0.3.6
    imageID: docker-pullable://k8s.gcr.io/metrics-server-amd64@sha256:c9c4e95068b51d6b33a9dccc61875df07dc650abbf4ac1a19d58b4628f89288b
    lastState: {}
    name: metrics-server
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-11-11T14:42:48Z"
  - containerID: docker://ca7c0d03a49a4a68c1f4cf272d38d17a87b3947d9288ba52bd16d73539af93b5
    image: asia.gcr.io/gke-release-staging/addon-resizer:1.8.8-gke.1
    imageID: docker-pullable://asia.gcr.io/gke-release-staging/addon-resizer@sha256:c6b0e87d835086b7e1f6fcf148611358534a8081e6489c8fee9c79c6597a4ee3
    lastState: {}
    name: metrics-server-nanny
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-11-11T14:42:52Z"
  hostIP: 10.128.0.5
  phase: Running
  podIP: 10.8.5.246
  podIPs:
  - ip: 10.8.5.246
  qosClass: Burstable
  startTime: "2020-11-11T14:42:35Z"
