apiVersion: v1
kind: Pod
metadata:
  annotations:
    components.gke.io/component-name: netd
    components.gke.io/component-version: 1.0.7
  creationTimestamp: "2020-11-07T03:12:57Z"
  generateName: netd-
  labels:
    controller-revision-hash: d94dd5d6b
    k8s-app: netd
    pod-template-generation: "1"
  name: netd-nvnsl
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: netd
    uid: e7a2d0c1-0fd8-4805-b3fa-19edb0c6c840
  resourceVersion: "22545968"
  selfLink: /api/v1/namespaces/kube-system/pods/netd-nvnsl
  uid: 6bfb7a25-ce7a-459f-b1cd-6dd076e8112c
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - gke-jstrachan-tekton-default-pool-154aeb80-pmxj
  containers:
  - args:
    - --enable-policy-routing=$(ENABLE_POLICY_ROUTING)
    - --logtostderr
    - --reconcile-interval-seconds=$(RECONCILE_INTERVAL_SECONDS)
    - --metrics-collectors=$(METRICS_COLLECTORS)
    - --metrics-address=$(METRICS_ADDRESS)
    env:
    - name: ENABLE_POLICY_ROUTING
      value: "false"
    - name: RECONCILE_INTERVAL_SECONDS
      valueFrom:
        configMapKeyRef:
          key: reconcile_interval_seconds
          name: netd-config
    - name: METRICS_COLLECTORS
      valueFrom:
        configMapKeyRef:
          key: metrics_collectors
          name: networking-metrics-config
    - name: METRICS_ADDRESS
      valueFrom:
        configMapKeyRef:
          key: metrics_address
          name: networking-metrics-config
    image: gke.gcr.io/netd-amd64:v0.2.7-gke.0
    imagePullPolicy: Always
    name: netd
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: netd-token-fdlbs
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  initContainers:
  - command:
    - sh
    - /install-cni.sh
    env:
    - name: CNI_SPEC_TEMPLATE
      valueFrom:
        configMapKeyRef:
          key: cni_spec_template
          name: netd-config
    - name: CNI_SPEC_NAME
      valueFrom:
        configMapKeyRef:
          key: cni_spec_name
          name: netd-config
    - name: ENABLE_CALICO_NETWORK_POLICY
      valueFrom:
        configMapKeyRef:
          key: enable_calico_network_policy
          name: netd-config
    - name: ENABLE_PRIVATE_IPV6_ACCESS
      valueFrom:
        configMapKeyRef:
          key: enable_private_ipv6_access
          name: netd-config
    - name: ENABLE_MASQUERADE
      valueFrom:
        configMapKeyRef:
          key: enable_masquerade
          name: netd-config
    - name: ENABLE_BANDWIDTH_PLUGIN
      valueFrom:
        configMapKeyRef:
          key: enable_bandwidth_plugin
          name: netd-config
    - name: ENABLE_CILIUM_PLUGIN
      valueFrom:
        configMapKeyRef:
          key: enable_cilium_plugin
          name: netd-config
    image: gke.gcr.io/netd-amd64:v0.2.7-gke.0
    imagePullPolicy: IfNotPresent
    name: install-cni
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /host/etc/cni/net.d
      name: cni-net-dir
    - mountPath: /host/home/kubernetes/bin
      name: kubernetes-bin
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: netd-token-fdlbs
      readOnly: true
  nodeName: gke-jstrachan-tekton-default-pool-154aeb80-pmxj
  nodeSelector:
    beta.kubernetes.io/os: linux
    cloud.google.com/gke-netd-ready: "true"
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: netd
  serviceAccountName: netd
  terminationGracePeriodSeconds: 0
  tolerations:
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists
  - key: components.gke.io/gke-managed-components
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    operator: Exists
  volumes:
  - hostPath:
      path: /etc/cni/net.d
      type: ""
    name: cni-net-dir
  - hostPath:
      path: /home/kubernetes/bin
      type: Directory
    name: kubernetes-bin
  - name: netd-token-fdlbs
    secret:
      defaultMode: 420
      secretName: netd-token-fdlbs
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-07T03:13:10Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-07T03:13:19Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-07T03:13:19Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-07T03:12:57Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://9678d461e085f6184396620f71710b907eaf76b3222b8971c86d0c859f60a95c
    image: gke.gcr.io/netd-amd64:v0.2.7-gke.0
    imageID: docker-pullable://gke.gcr.io/netd-amd64@sha256:ff488d2d9cc4a7bfd64fceabf36de05542f5fabe26b07dbd33d9cc2f693a74fd
    lastState: {}
    name: netd
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-11-07T03:13:18Z"
  hostIP: 10.128.0.11
  initContainerStatuses:
  - containerID: docker://8b116348eacffcf8652786f43b14f87aff231ff89d7aeeaa584d0efa5b89ec3a
    image: gke.gcr.io/netd-amd64:v0.2.7-gke.0
    imageID: docker-pullable://gke.gcr.io/netd-amd64@sha256:ff488d2d9cc4a7bfd64fceabf36de05542f5fabe26b07dbd33d9cc2f693a74fd
    lastState: {}
    name: install-cni
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://8b116348eacffcf8652786f43b14f87aff231ff89d7aeeaa584d0efa5b89ec3a
        exitCode: 0
        finishedAt: "2020-11-07T03:13:10Z"
        reason: Completed
        startedAt: "2020-11-07T03:13:09Z"
  phase: Running
  podIP: 10.128.0.11
  podIPs:
  - ip: 10.128.0.11
  qosClass: BestEffort
  startTime: "2020-11-07T03:12:57Z"
