apiVersion: project.jenkins-x.io/v1alpha1
kind: PipelineCatalog
spec:
  repositories:
  - label: My Pipeline Catalog
    gitUrl: https://github.com/jenkins-x/jxr-packs-kubernetes
  - label: JX3 Pipeline Catalog
    gitUrl: https://github.com/jstrachan/jx3-pipeline-catalog
