apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        cb-kubecd/bdd-gh-1602679032: true
        jstrachan/jx-demo-terraform-dev: true
        jstrachan/nodey533: true
        jstrachan/nodey534: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        cb-kubecd/bdd-gh-1602679032: merge
        jstrachan/jx-demo-terraform-dev: merge
        jstrachan/nodey533: merge
        jstrachan/nodey534: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jstrachan/jx-demo-terraform-dev
        - cb-kubecd/bdd-gh-1602679032
        - jstrachan/nodey533
        - jstrachan/nodey534
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jstrachan/jx-demo-terraform-dev
        - cb-kubecd/bdd-gh-1602679032
        - jstrachan/nodey533
        - jstrachan/nodey534
      target_url: http://dashboard-jx.35.184.150.204.nip.io
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
