apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        jstrachan/jx-demo-terraform-dev: true
        jstrachan/knative-quickstart: true
        jstrachan/nodey533: true
        jstrachan/nodey536: true
        jstrachan/nodey542: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        jstrachan/jx-demo-terraform-dev: merge
        jstrachan/knative-quickstart: merge
        jstrachan/nodey533: merge
        jstrachan/nodey536: merge
        jstrachan/nodey542: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jstrachan/jx-demo-terraform-dev
        - jstrachan/knative-quickstart
        - jstrachan/nodey533
        - jstrachan/nodey536
        - jstrachan/nodey542
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jstrachan/jx-demo-terraform-dev
        - jstrachan/knative-quickstart
        - jstrachan/nodey533
        - jstrachan/nodey536
        - jstrachan/nodey542
      target_url: http://dashboard-jx.34.105.200.93.nip.io
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
