apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  labels:
    name: istio-system
    gitops.jenkins-x.io/pipeline: 'cluster'
    team: 'jx'
  name: istio-system
spec: {}
status: {}
