apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  labels:
    name: knative-serving
    gitops.jenkins-x.io/pipeline: 'cluster'
    team: 'jx'
  name: knative-serving
spec: {}
status: {}
