# Source: nodey533/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-10-13T07:48:27Z"
  deletionTimestamp: null
  name: 'nodey533-1.0.0'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      branch: master
      committer:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      message: |
        release 1.0.0
      sha: b1705c3500827e86865648982502f1edd4795511
    - author:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      branch: master
      committer:
        accountReference:
          - id: jstrachan-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      message: |
        release 1.0.0
      sha: 5b60af10d90cc9f1b7fb666ee183aa762d6ad51b
    - author:
        accountReference:
          - provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        Jenkins X build pack
      sha: 4d8e3620e50924f7e0d8567f28d41131ee556d5d
  gitCloneUrl: https://github.com/jstrachan/nodey533.git
  gitHttpUrl: https://github.com/jstrachan/nodey533
  gitOwner: jstrachan
  gitRepository: nodey533
  name: 'nodey533'
  releaseNotesURL: https://github.com/jstrachan/nodey533/releases/tag/v1.0.0
  version: v1.0.0
status: {}
