# Source: nodey542/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-11-24T17:36:01Z"
  deletionTimestamp: null
  name: 'nodey542-2.0.1304'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: jenkins-x-bot-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        accountReference:
          - id: jenkins-x-bot-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        release 2.0.1304
      sha: 6e7018d57885fa69403714cd19b7e57ef6652d6b
    - author:
        accountReference:
          - id: jenkins-x-bot-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        accountReference:
          - id: jenkins-x-bot-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: added variables
      sha: ccaa51b97a288a7aed914790214bb4b669d41621
    - author:
        accountReference:
          - id: jenkins-x-bot-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        accountReference:
          - id: jenkins-x-bot-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        release 2.0.1304
      sha: 06d82ab5d4aac9c189ec18ecab437978a864e9ae
    - author:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        fix: latest mink
      sha: 690a3d52f2afc5324c52a59699bc09eda89b07df
    - author:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        fix: plain kaniko
      sha: 92588e45bd05f746f689470ccf872cc9c73a6ee8
    - author:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        fix: plain kaniko
      sha: 5c05099bbf22f52dc5fb9ffa69f4452c347530ba
    - author:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        fix: plain kaniko
      sha: 16b7ea8009f5549b1bda55518ae2454491f64c34
  gitCloneUrl: https://github.com/jstrachan/nodey542.git
  gitHttpUrl: https://github.com/jstrachan/nodey542
  gitOwner: jstrachan
  gitRepository: nodey542
  name: 'nodey542'
  releaseNotesURL: https://github.com/jstrachan/nodey542/releases/tag/v2.0.1304
  version: v2.0.1304
status: {}
