apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: jstrachan
    provider: https://github.com
    providerKind: github
    repositories:
    - name: nodey533
    - name: nodey534
    - name: nodey536
    scheduler: in-repo
  - owner: cb-kubecd
    provider: https://github.com
    providerKind: github
    repositories:
    - name: bdd-gh-1602679032
    scheduler: in-repo
