# Source: chartmuseum/templates/secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: chartmuseum-chartmuseum
  labels:
    app: chartmuseum
    chart: chartmuseum-2.6.0
    heritage: "Helm"
    release: "chartmuseum"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  backendType: gcpSecretsManager
  projectId: jenkins-x-labs-bdd
  data:
    - name: BASIC_AUTH_PASS
      key: jstrachan-tekton-chartmuseum-chartmuseum
      version: latest
    - name: BASIC_AUTH_USER
      key: jstrachan-tekton-chartmuseum-chartmuseum
      version: latest
  template:
    metadata:
      labels:
        app: chartmuseum
        chart: chartmuseum-2.6.0
        heritage: "Helm"
        release: "chartmuseum"
    type: Opaque
