# Source: nodey544/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-12-07T11:54:19Z"
  deletionTimestamp: null
  name: 'nodey544-1.0.1'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: 4644d1572a9819e9c36b367a9defc66b51154ee9
    - author:
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        chore: Jenkins X build pack
      sha: ef6868ac636fc6801f140ab294e602b8626f40d7
  gitHttpUrl: https://github.com/jstrachan/nodey544
  gitOwner: jstrachan
  gitRepository: nodey544
  name: 'nodey544'
  releaseNotesURL: https://github.com/jstrachan/nodey544/releases/tag/v1.0.1
  version: v1.0.1
status: {}
