apiVersion: v1
kind: Pod
metadata:
  annotations:
    wave.pusher.com/config-hash: 100444e91862dd77d7ebe29f050c1e9a7f357c771e1a7b7650aae27e6a3a031d
  creationTimestamp: "2020-11-07T03:23:09Z"
  generateName: nodey536-nodey536-558695b556-
  labels:
    app: nodey536-nodey536
    draft: draft-app
    pod-template-hash: 558695b556
  name: nodey536-nodey536-558695b556-266sn
  namespace: jx-staging
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: nodey536-nodey536-558695b556
    uid: da3d4bb3-4b3f-4596-bacd-91ba53c5b8df
  resourceVersion: "27446113"
  selfLink: /api/v1/namespaces/jx-staging/pods/nodey536-nodey536-558695b556-266sn
  uid: 2b20f443-4a98-463c-acbf-d0761a924ca2
spec:
  containers:
  - image: gcr.io/jenkins-x-labs-bdd/nodey536:1.0.5
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: nodey536
    ports:
    - containerPort: 8080
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 8080
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 400m
        memory: 256Mi
      requests:
        cpu: 200m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-d5sdk
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-jstrachan-tekton-nap-n1-standard--0a7ecf20-446q
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-d5sdk
    secret:
      defaultMode: 420
      secretName: default-token-d5sdk
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-07T03:23:09Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-07T03:23:09Z"
    message: 'containers with unready status: [nodey536]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-07T03:23:09Z"
    message: 'containers with unready status: [nodey536]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-07T03:23:09Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: gcr.io/jenkins-x-labs-bdd/nodey536:1.0.5
    imageID: ""
    lastState: {}
    name: nodey536
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "gcr.io/jenkins-x-labs-bdd/nodey536:1.0.5"
        reason: ImagePullBackOff
  hostIP: 10.128.0.14
  phase: Pending
  podIP: 10.8.8.2
  podIPs:
  - ip: 10.8.8.2
  qosClass: Burstable
  startTime: "2020-11-07T03:23:09Z"
