apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-11-11T14:21:03Z"
  generateName: check-reaper-1605104460-
  labels:
    controller-uid: c07f2a27-6fa5-4154-a030-4810faa95264
    job-name: check-reaper-1605104460
  name: check-reaper-1605104460-khsp6
  namespace: kuberhealthy
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: check-reaper-1605104460
    uid: c07f2a27-6fa5-4154-a030-4810faa95264
  resourceVersion: "27444327"
  selfLink: /api/v1/namespaces/kuberhealthy/pods/check-reaper-1605104460-khsp6
  uid: 2037e440-b88c-4988-b120-5fc4fcbbdda4
spec:
  containers:
  - env:
    - name: SINGLE_NAMESPACE
    - name: MAX_PODS_THRESHOLD
      value: "4"
    - name: JOB_DELETE_TIME_DURATION
      value: 15m
    image: kuberhealthy/check-reaper:v1.5.0
    imagePullPolicy: IfNotPresent
    name: check-reaper
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 999
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: check-reaper-token-x2jn2
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-jstrachan-tekton-nap-n1-standard--0a7ecf20-446q
  priority: 0
  restartPolicy: OnFailure
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: check-reaper
  serviceAccountName: check-reaper
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: check-reaper-token-x2jn2
    secret:
      defaultMode: 420
      secretName: check-reaper-token-x2jn2
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:21:03Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:21:03Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:21:03Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:21:03Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://ea5e5a0342677c3a8df5a54af4f4f4a9c72233b7649308d1a2b2198ab828ae83
    image: kuberhealthy/check-reaper:v1.5.0
    imageID: docker-pullable://kuberhealthy/check-reaper@sha256:0ed616550b90a95ff2aa13636137516ee958da0086b9f23f2d38b424c8bf7916
    lastState: {}
    name: check-reaper
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://ea5e5a0342677c3a8df5a54af4f4f4a9c72233b7649308d1a2b2198ab828ae83
        exitCode: 0
        finishedAt: "2020-11-11T14:21:04Z"
        reason: Completed
        startedAt: "2020-11-11T14:21:04Z"
  hostIP: 10.128.0.14
  phase: Succeeded
  podIP: 10.8.8.234
  podIPs:
  - ip: 10.8.8.234
  qosClass: Burstable
  startTime: "2020-11-11T14:21:03Z"
