apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-11-11T14:00:04Z"
  generateName: check-reaper-1605103200-
  labels:
    controller-uid: 6fcc2f8d-5fc8-4f13-8845-2e8194a98b99
    job-name: check-reaper-1605103200
  name: check-reaper-1605103200-6qp5t
  namespace: kuberhealthy
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: check-reaper-1605103200
    uid: 6fcc2f8d-5fc8-4f13-8845-2e8194a98b99
  resourceVersion: "27431675"
  selfLink: /api/v1/namespaces/kuberhealthy/pods/check-reaper-1605103200-6qp5t
  uid: 385a0b1b-24ac-46e5-bdb4-343d46c7b977
spec:
  containers:
  - env:
    - name: SINGLE_NAMESPACE
    - name: MAX_PODS_THRESHOLD
      value: "4"
    - name: JOB_DELETE_TIME_DURATION
      value: 15m
    image: kuberhealthy/check-reaper:v1.5.0
    imagePullPolicy: IfNotPresent
    name: check-reaper
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 999
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: check-reaper-token-x2jn2
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-jstrachan-tekton-default-pool-154aeb80-n21q
  priority: 0
  restartPolicy: OnFailure
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: check-reaper
  serviceAccountName: check-reaper
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: check-reaper-token-x2jn2
    secret:
      defaultMode: 420
      secretName: check-reaper-token-x2jn2
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:00:04Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:00:04Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:00:04Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:00:04Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://efc0db0852cc572beb0b7cb6fb8508cf9b8845868d710eebf77957850fac9a33
    image: kuberhealthy/check-reaper:v1.5.0
    imageID: docker-pullable://kuberhealthy/check-reaper@sha256:0ed616550b90a95ff2aa13636137516ee958da0086b9f23f2d38b424c8bf7916
    lastState: {}
    name: check-reaper
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://efc0db0852cc572beb0b7cb6fb8508cf9b8845868d710eebf77957850fac9a33
        exitCode: 0
        finishedAt: "2020-11-11T14:00:05Z"
        reason: Completed
        startedAt: "2020-11-11T14:00:05Z"
  hostIP: 10.128.0.5
  phase: Succeeded
  podIP: 10.8.5.227
  podIPs:
  - ip: 10.8.5.227
  qosClass: Burstable
  startTime: "2020-11-11T14:00:04Z"
