apiVersion: v1
kind: Pod
metadata:
  annotations:
    comcast.github.io/check-name: deployment
  creationTimestamp: "2020-11-11T13:09:19Z"
  labels:
    app: kuberhealthy-check
    kuberhealthy-check-name: deployment
    kuberhealthy-run-id: 0c4f75c3-ded9-4a63-ae4a-8c7f6aba4a22
  name: deployment-1605100152
  namespace: kuberhealthy
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: kuberhealthy-5c46966647-6db64
    uid: d98a024b-7504-4cdd-a3bb-c70c6128d8fb
  resourceVersion: "27400872"
  selfLink: /api/v1/namespaces/kuberhealthy/pods/deployment-1605100152
  uid: 9e76a9c1-8683-4ab6-a849-c6f0972d022b
spec:
  containers:
  - env:
    - name: CHECK_DEPLOYMENT_REPLICAS
      value: "4"
    - name: CHECK_DEPLOYMENT_ROLLING_UPDATE
      value: "true"
    - name: CHECK_SERVICE_ACCOUNT
      value: default
    - name: KH_REPORTING_URL
      value: http://kuberhealthy.kuberhealthy.svc.cluster.local/externalCheckStatus
    - name: KH_RUN_UUID
      value: 0c4f75c3-ded9-4a63-ae4a-8c7f6aba4a22
    - name: KH_CHECK_RUN_DEADLINE
      value: "1605101054"
    - name: KH_POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: kuberhealthy/deployment-check:v1.6.2
    imagePullPolicy: IfNotPresent
    name: deployment
    resources:
      limits:
        cpu: 40m
      requests:
        cpu: 25m
        memory: 15Mi
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: deployment-sa-token-jzgz5
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-jstrachan-tekton-default-pool-154aeb80-pmxj
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 999
    runAsUser: 999
  serviceAccount: deployment-sa
  serviceAccountName: deployment-sa
  terminationGracePeriodSeconds: 60
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: deployment-sa-token-jzgz5
    secret:
      defaultMode: 420
      secretName: deployment-sa-token-jzgz5
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:09:19Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:10:28Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:10:28Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:09:19Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://12efe35a3ce2837df54a6dafe87ce022d6cabb65856d793215923fc424ad3cc3
    image: kuberhealthy/deployment-check:v1.6.2
    imageID: docker-pullable://kuberhealthy/deployment-check@sha256:19ad1a5255b0d0c6d2f3b8f31759f986c3b832d2a4b39a2056a6d05140e3f761
    lastState: {}
    name: deployment
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://12efe35a3ce2837df54a6dafe87ce022d6cabb65856d793215923fc424ad3cc3
        exitCode: 0
        finishedAt: "2020-11-11T13:10:27Z"
        reason: Completed
        startedAt: "2020-11-11T13:09:21Z"
  hostIP: 10.128.0.11
  phase: Succeeded
  podIP: 10.8.7.119
  podIPs:
  - ip: 10.8.7.119
  qosClass: Burstable
  startTime: "2020-11-11T13:09:19Z"
