apiVersion: v1
kind: Pod
metadata:
  annotations:
    comcast.github.io/check-name: dns-status-internal
  creationTimestamp: "2020-11-11T14:21:16Z"
  labels:
    app: kuberhealthy-check
    kuberhealthy-check-name: dns-status-internal
    kuberhealthy-run-id: 9e467ec8-45e3-4b63-a3a1-1b92386a15cf
  name: dns-status-internal-1605104471
  namespace: kuberhealthy
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: kuberhealthy-5c46966647-6db64
    uid: d98a024b-7504-4cdd-a3bb-c70c6128d8fb
  resourceVersion: "27444507"
  selfLink: /api/v1/namespaces/kuberhealthy/pods/dns-status-internal-1605104471
  uid: a69024bf-5db3-486f-b838-3d349679b28f
spec:
  containers:
  - env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: HOSTNAME
      value: kubernetes.default
    - name: KH_REPORTING_URL
      value: http://kuberhealthy.kuberhealthy.svc.cluster.local/externalCheckStatus
    - name: KH_RUN_UUID
      value: 9e467ec8-45e3-4b63-a3a1-1b92386a15cf
    - name: KH_CHECK_RUN_DEADLINE
      value: "1605105371"
    - name: KH_POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: kuberhealthy/dns-resolution-check:v1.4.1
    imagePullPolicy: IfNotPresent
    name: main
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-k5bp8
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-jstrachan-tekton-default-pool-154aeb80-pmxj
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 999
    runAsUser: 999
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-k5bp8
    secret:
      defaultMode: 420
      secretName: default-token-k5bp8
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:21:16Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:21:20Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:21:20Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:21:16Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://bc405a40c4599c4c8de12d7a945c2d2621ccbdb61dddcabc8f3d7a7e35a04fae
    image: kuberhealthy/dns-resolution-check:v1.4.1
    imageID: docker-pullable://kuberhealthy/dns-resolution-check@sha256:91b80a863e44e5a341844f85c5bb057be1334e6491ce2207c9747e0f4ea396dd
    lastState: {}
    name: main
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://bc405a40c4599c4c8de12d7a945c2d2621ccbdb61dddcabc8f3d7a7e35a04fae
        exitCode: 0
        finishedAt: "2020-11-11T14:21:20Z"
        reason: Completed
        startedAt: "2020-11-11T14:21:18Z"
  hostIP: 10.128.0.11
  phase: Succeeded
  podIP: 10.8.7.88
  podIPs:
  - ip: 10.8.7.88
  qosClass: Burstable
  startTime: "2020-11-11T14:21:16Z"
