apiVersion: v1
kind: Pod
metadata:
  annotations:
    comcast.github.io/check-name: dns-status-internal
  creationTimestamp: "2020-11-11T14:07:16Z"
  labels:
    app: kuberhealthy-check
    kuberhealthy-check-name: dns-status-internal
    kuberhealthy-run-id: 9f1cfa25-d53d-4b28-9871-57d9d0402fe9
  name: dns-status-internal-1605103631
  namespace: kuberhealthy
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: kuberhealthy-5c46966647-6db64
    uid: d98a024b-7504-4cdd-a3bb-c70c6128d8fb
  resourceVersion: "27435899"
  selfLink: /api/v1/namespaces/kuberhealthy/pods/dns-status-internal-1605103631
  uid: 9a4174d3-e0ff-488b-906c-4b054024d741
spec:
  containers:
  - env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: HOSTNAME
      value: kubernetes.default
    - name: KH_REPORTING_URL
      value: http://kuberhealthy.kuberhealthy.svc.cluster.local/externalCheckStatus
    - name: KH_RUN_UUID
      value: 9f1cfa25-d53d-4b28-9871-57d9d0402fe9
    - name: KH_CHECK_RUN_DEADLINE
      value: "1605104531"
    - name: KH_POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: kuberhealthy/dns-resolution-check:v1.4.1
    imagePullPolicy: IfNotPresent
    name: main
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-k5bp8
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-jstrachan-tekton-nap-n1-standard--0a7ecf20-446q
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 999
    runAsUser: 999
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-k5bp8
    secret:
      defaultMode: 420
      secretName: default-token-k5bp8
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:07:16Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:07:19Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:07:19Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:07:16Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://fbfd73db43a1786483b2e3cae2f0804cb05c0b432e9c8dbb6f2e74c05e296d57
    image: kuberhealthy/dns-resolution-check:v1.4.1
    imageID: docker-pullable://kuberhealthy/dns-resolution-check@sha256:91b80a863e44e5a341844f85c5bb057be1334e6491ce2207c9747e0f4ea396dd
    lastState: {}
    name: main
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://fbfd73db43a1786483b2e3cae2f0804cb05c0b432e9c8dbb6f2e74c05e296d57
        exitCode: 0
        finishedAt: "2020-11-11T14:07:18Z"
        reason: Completed
        startedAt: "2020-11-11T14:07:17Z"
  hostIP: 10.128.0.14
  phase: Succeeded
  podIP: 10.8.8.208
  podIPs:
  - ip: 10.8.8.208
  qosClass: Burstable
  startTime: "2020-11-11T14:07:16Z"
