apiVersion: v1
kind: Pod
metadata:
  annotations:
    comcast.github.io/check-name: jx-secrets
  creationTimestamp: "2020-11-11T14:30:34Z"
  labels:
    app: kuberhealthy-check
    kuberhealthy-check-name: jx-secrets
    kuberhealthy-run-id: 9274974a-5b82-4e2c-8f41-5e912688f316
  name: jx-secrets-1605105029
  namespace: kuberhealthy
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: kuberhealthy-5c46966647-6db64
    uid: d98a024b-7504-4cdd-a3bb-c70c6128d8fb
  resourceVersion: "27450039"
  selfLink: /api/v1/namespaces/kuberhealthy/pods/jx-secrets-1605105029
  uid: 11df1b56-1c46-4680-b1e9-553f7cde0357
spec:
  containers:
  - env:
    - name: KH_REPORTING_URL
      value: http://kuberhealthy.kuberhealthy.svc.cluster.local/externalCheckStatus
    - name: KH_RUN_UUID
      value: 9274974a-5b82-4e2c-8f41-5e912688f316
    - name: KH_CHECK_RUN_DEADLINE
      value: "1605105329"
    - name: KH_POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: gcr.io/jenkinsxio/jx-secrets:0.0.51
    imagePullPolicy: IfNotPresent
    name: main
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: jx-secrets-sa-token-7ktpt
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-jstrachan-tekton-default-pool-154aeb80-pmxj
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 999
    runAsUser: 999
  serviceAccount: jx-secrets-sa
  serviceAccountName: jx-secrets-sa
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: jx-secrets-sa-token-7ktpt
    secret:
      defaultMode: 420
      secretName: jx-secrets-sa-token-7ktpt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:30:34Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:30:38Z"
    message: 'containers with unready status: [main]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:30:38Z"
    message: 'containers with unready status: [main]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:30:34Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://fe51315bc326716e1b594c1549d8a9ca8ba22adba018fef7719e1150f7f66aae
    image: gcr.io/jenkinsxio/jx-secrets:0.0.51
    imageID: docker-pullable://gcr.io/jenkinsxio/jx-secrets@sha256:6586bc01b19d91f4dcf7190a500740e4319ff1dba7ad997f7d6e57d7b52c70d2
    lastState: {}
    name: main
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://fe51315bc326716e1b594c1549d8a9ca8ba22adba018fef7719e1150f7f66aae
        exitCode: 2
        finishedAt: "2020-11-11T14:30:37Z"
        reason: Error
        startedAt: "2020-11-11T14:30:35Z"
  hostIP: 10.128.0.11
  phase: Failed
  podIP: 10.8.7.130
  podIPs:
  - ip: 10.8.7.130
  qosClass: Burstable
  startTime: "2020-11-11T14:30:34Z"
