apiVersion: v1
kind: Pod
metadata:
  annotations:
    comcast.github.io/check-name: jx-secrets
  creationTimestamp: "2020-11-11T13:16:16Z"
  labels:
    app: kuberhealthy-check
    kuberhealthy-check-name: jx-secrets
    kuberhealthy-run-id: 442df2c9-bdd9-47f7-9e9f-5d1a9956bceb
  name: jx-secrets-1605100571
  namespace: kuberhealthy
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: kuberhealthy-5c46966647-6db64
    uid: d98a024b-7504-4cdd-a3bb-c70c6128d8fb
  resourceVersion: "27405251"
  selfLink: /api/v1/namespaces/kuberhealthy/pods/jx-secrets-1605100571
  uid: 07563769-4019-4078-b53e-4950dbfec5b8
spec:
  containers:
  - env:
    - name: KH_REPORTING_URL
      value: http://kuberhealthy.kuberhealthy.svc.cluster.local/externalCheckStatus
    - name: KH_RUN_UUID
      value: 442df2c9-bdd9-47f7-9e9f-5d1a9956bceb
    - name: KH_CHECK_RUN_DEADLINE
      value: "1605100871"
    - name: KH_POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: gcr.io/jenkinsxio/jx-secrets:0.0.51
    imagePullPolicy: IfNotPresent
    name: main
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: jx-secrets-sa-token-7ktpt
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-jstrachan-tekton-nap-n1-standard--0a7ecf20-446q
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 999
    runAsUser: 999
  serviceAccount: jx-secrets-sa
  serviceAccountName: jx-secrets-sa
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: jx-secrets-sa-token-7ktpt
    secret:
      defaultMode: 420
      secretName: jx-secrets-sa-token-7ktpt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:16:16Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:16:19Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:16:19Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:16:16Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://62055050a742d1c419e21a0e15ab349b0c26d6bf3d6d0bd00c2bdc039f2e8b4c
    image: gcr.io/jenkinsxio/jx-secrets:0.0.51
    imageID: docker-pullable://gcr.io/jenkinsxio/jx-secrets@sha256:6586bc01b19d91f4dcf7190a500740e4319ff1dba7ad997f7d6e57d7b52c70d2
    lastState: {}
    name: main
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://62055050a742d1c419e21a0e15ab349b0c26d6bf3d6d0bd00c2bdc039f2e8b4c
        exitCode: 0
        finishedAt: "2020-11-11T13:16:18Z"
        reason: Completed
        startedAt: "2020-11-11T13:16:17Z"
  hostIP: 10.128.0.14
  phase: Succeeded
  podIP: 10.8.8.143
  podIPs:
  - ip: 10.8.8.143
  qosClass: Burstable
  startTime: "2020-11-11T13:16:16Z"
