apiVersion: v1
kind: Pod
metadata:
  annotations:
    comcast.github.io/check-name: jx-secrets
  creationTimestamp: "2020-11-11T14:35:35Z"
  labels:
    app: kuberhealthy-check
    kuberhealthy-check-name: jx-secrets
    kuberhealthy-run-id: a73077b7-472e-4f29-9622-b34b33bc7e88
  name: jx-secrets-1605105330
  namespace: kuberhealthy
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: kuberhealthy-5c46966647-6db64
    uid: d98a024b-7504-4cdd-a3bb-c70c6128d8fb
  resourceVersion: "27452845"
  selfLink: /api/v1/namespaces/kuberhealthy/pods/jx-secrets-1605105330
  uid: 4ba1a05b-5882-488f-aff5-9b07c629f43f
spec:
  containers:
  - env:
    - name: KH_REPORTING_URL
      value: http://kuberhealthy.kuberhealthy.svc.cluster.local/externalCheckStatus
    - name: KH_RUN_UUID
      value: a73077b7-472e-4f29-9622-b34b33bc7e88
    - name: KH_CHECK_RUN_DEADLINE
      value: "1605105630"
    - name: KH_POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: gcr.io/jenkinsxio/jx-secrets:0.0.51
    imagePullPolicy: IfNotPresent
    name: main
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: jx-secrets-sa-token-7ktpt
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-jstrachan-tekton-default-pool-154aeb80-pmxj
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 999
    runAsUser: 999
  serviceAccount: jx-secrets-sa
  serviceAccountName: jx-secrets-sa
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: jx-secrets-sa-token-7ktpt
    secret:
      defaultMode: 420
      secretName: jx-secrets-sa-token-7ktpt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:35:36Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:35:36Z"
    message: 'containers with unready status: [main]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:35:36Z"
    message: 'containers with unready status: [main]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T14:35:35Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://b971410959b2b26db6f27d8b003879b770101fe1ddd7e693da4dd9ae50d05793
    image: gcr.io/jenkinsxio/jx-secrets:0.0.51
    imageID: docker-pullable://gcr.io/jenkinsxio/jx-secrets@sha256:6586bc01b19d91f4dcf7190a500740e4319ff1dba7ad997f7d6e57d7b52c70d2
    lastState: {}
    name: main
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://b971410959b2b26db6f27d8b003879b770101fe1ddd7e693da4dd9ae50d05793
        exitCode: 2
        finishedAt: "2020-11-11T14:35:36Z"
        reason: Error
        startedAt: "2020-11-11T14:35:36Z"
  hostIP: 10.128.0.11
  phase: Failed
  podIP: 10.8.7.146
  podIPs:
  - ip: 10.8.7.146
  qosClass: Burstable
  startTime: "2020-11-11T14:35:36Z"
