apiVersion: v1
kind: Pod
metadata:
  annotations:
    wave.pusher.com/config-hash: 2e8d6114911b00e8c3ad29efe40e28cfd65815273b23a6d72a3c09d2be2c811f
  creationTimestamp: "2020-11-07T03:04:13Z"
  generateName: jenkins-x-chartmuseum-844cddb458-
  labels:
    app: chartmuseum
    pod-template-hash: 844cddb458
    release: chartmuseum
  name: jenkins-x-chartmuseum-844cddb458-2mnfm
  namespace: jx
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: jenkins-x-chartmuseum-844cddb458
    uid: b0e4bd62-d790-4399-ae59-bd21c3fc1a06
  resourceVersion: "22539096"
  selfLink: /api/v1/namespaces/jx/pods/jenkins-x-chartmuseum-844cddb458-2mnfm
  uid: c1996b27-7b3f-43c5-b7be-9f3d26f8ffe0
spec:
  containers:
  - args:
    - --port=8080
    - --storage-local-rootdir=/storage
    env:
    - name: AUTH_ANONYMOUS_GET
      value: "true"
    - name: CHART_POST_FORM_FIELD_NAME
      value: chart
    - name: DISABLE_METRICS
      value: "true"
    - name: LOG_JSON
      value: "true"
    - name: PROV_POST_FORM_FIELD_NAME
      value: prov
    - name: STORAGE
      value: local
    - name: BASIC_AUTH_PASS
      valueFrom:
        secretKeyRef:
          key: BASIC_AUTH_PASS
          name: jenkins-x-chartmuseum
    - name: BASIC_AUTH_USER
      valueFrom:
        secretKeyRef:
          key: BASIC_AUTH_USER
          name: jenkins-x-chartmuseum
    image: chartmuseum/chartmuseum:v0.7.1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: http
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: chartmuseum
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: http
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 160m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /storage
      name: storage-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-gddcm
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-jstrachan-tekton-default-pool-154aeb80-ccfi
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: storage-volume
    persistentVolumeClaim:
      claimName: jenkins-x-chartmuseum
  - name: default-token-gddcm
    secret:
      defaultMode: 420
      secretName: default-token-gddcm
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-07T03:04:14Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-07T03:05:15Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-07T03:05:15Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-07T03:04:13Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://cbb4301b422fb68df6c5c00d4922752cc83afd7506a2b64ce6165790c7a1fe9a
    image: chartmuseum/chartmuseum:v0.7.1
    imageID: docker-pullable://chartmuseum/chartmuseum@sha256:e8b9a9206d14cb61be15a2956d356679d8305f9a972b9cc8b84261d7becd0bf4
    lastState: {}
    name: chartmuseum
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-11-07T03:05:08Z"
  hostIP: 10.128.0.2
  phase: Running
  podIP: 10.8.3.8
  podIPs:
  - ip: 10.8.3.8
  qosClass: Burstable
  startTime: "2020-11-07T03:04:14Z"
