apiVersion: v1
kind: Pod
metadata:
  annotations:
    comcast.github.io/check-name: jx-bot-token
  creationTimestamp: "2020-11-11T13:27:16Z"
  labels:
    app: kuberhealthy-check
    kuberhealthy-check-name: jx-bot-token
    kuberhealthy-run-id: fe5389bb-2a1d-488d-a622-1b39633ecb5c
  name: jx-bot-token-1605101231
  namespace: jx
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: kuberhealthy-5c46966647-6db64
    uid: d98a024b-7504-4cdd-a3bb-c70c6128d8fb
  resourceVersion: "27412625"
  selfLink: /api/v1/namespaces/jx/pods/jx-bot-token-1605101231
  uid: 93cb66e3-4bfa-4ea4-ad3a-41380899959e
spec:
  containers:
  - env:
    - name: OAUTH_TOKEN
      valueFrom:
        secretKeyRef:
          key: password
          name: tekton-git
    - name: GIT_PROVIDER
      value: https://github.com
    - name: KH_REPORTING_URL
      value: http://kuberhealthy.kuberhealthy.svc.cluster.local/externalCheckStatus
    - name: KH_RUN_UUID
      value: fe5389bb-2a1d-488d-a622-1b39633ecb5c
    - name: KH_CHECK_RUN_DEADLINE
      value: "1605101351"
    - name: KH_POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: gcr.io/jenkinsxio/jx-bot-token:0.0.32
    imagePullPolicy: IfNotPresent
    name: jx-bot-token
    resources:
      limits:
        cpu: 40m
      requests:
        cpu: 25m
        memory: 15Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-gddcm
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-jstrachan-tekton-default-pool-154aeb80-pmxj
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 60
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-gddcm
    secret:
      defaultMode: 420
      secretName: default-token-gddcm
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:27:16Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:27:27Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:27:27Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:27:16Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://7242b9d07d6e9993a19328744aaebf31ba71598364edf30869f772f38e406d41
    image: gcr.io/jenkinsxio/jx-bot-token:0.0.32
    imageID: docker-pullable://gcr.io/jenkinsxio/jx-bot-token@sha256:6ceca5b1d0e07b4b0e05bc56f6fe6ab68fdb840f31fd294e863629ac91ef4401
    lastState: {}
    name: jx-bot-token
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://7242b9d07d6e9993a19328744aaebf31ba71598364edf30869f772f38e406d41
        exitCode: 0
        finishedAt: "2020-11-11T13:27:26Z"
        reason: Completed
        startedAt: "2020-11-11T13:27:20Z"
  hostIP: 10.128.0.11
  phase: Succeeded
  podIP: 10.8.7.165
  podIPs:
  - ip: 10.8.7.165
  qosClass: Burstable
  startTime: "2020-11-11T13:27:16Z"
