apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-11-11T13:30:01Z"
  generateName: jx-preview-gc-jobs-1605101400-
  labels:
    app: jx-preview-gc-jobs
    controller-uid: 17b8e62b-ff95-467c-b398-f665540f0651
    job-name: jx-preview-gc-jobs-1605101400
    release: jx-preview
  name: jx-preview-gc-jobs-1605101400-4ghf7
  namespace: jx
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: jx-preview-gc-jobs-1605101400
    uid: 17b8e62b-ff95-467c-b398-f665540f0651
  resourceVersion: "27414210"
  selfLink: /api/v1/namespaces/jx/pods/jx-preview-gc-jobs-1605101400-4ghf7
  uid: e6a8c157-2bb9-4f04-912b-93323600fcbd
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - jx gitops git setup --namespace jx --secret tekton-git && jx preview gc
    image: gcr.io/jenkinsxio/jx-cli:latest
    imagePullPolicy: IfNotPresent
    name: jx-preview-gc-jobs
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: jx-preview-gc-jobs-token-hvrbq
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-jstrachan-tekton-default-pool-154aeb80-pmxj
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: jx-preview-gc-jobs
  serviceAccountName: jx-preview-gc-jobs
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: jx-preview-gc-jobs-token-hvrbq
    secret:
      defaultMode: 420
      secretName: jx-preview-gc-jobs-token-hvrbq
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:30:01Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:30:01Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:30:01Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:30:01Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://1dc1ac4653b44f8bfc4026d9b52ab5b93895ef26888fe652ced7c2d90b74b4e4
    image: gcr.io/jenkinsxio/jx-cli:latest
    imageID: docker-pullable://gcr.io/jenkinsxio/jx-cli@sha256:fcd9bde5e3162d26e196b2cad77d76611a23a38207e4dc39e691b795c6815a7a
    lastState: {}
    name: jx-preview-gc-jobs
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://1dc1ac4653b44f8bfc4026d9b52ab5b93895ef26888fe652ced7c2d90b74b4e4
        exitCode: 0
        finishedAt: "2020-11-11T13:30:03Z"
        reason: Completed
        startedAt: "2020-11-11T13:30:02Z"
  hostIP: 10.128.0.11
  phase: Succeeded
  podIP: 10.8.7.177
  podIPs:
  - ip: 10.8.7.177
  qosClass: BestEffort
  startTime: "2020-11-11T13:30:01Z"
