apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-11-11T13:00:08Z"
  generateName: jx-preview-gc-jobs-1605099600-
  labels:
    app: jx-preview-gc-jobs
    controller-uid: 7e4db821-668a-47a5-962a-b784630520fc
    job-name: jx-preview-gc-jobs-1605099600
    release: jx-preview
  name: jx-preview-gc-jobs-1605099600-pxf66
  namespace: jx
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: jx-preview-gc-jobs-1605099600
    uid: 7e4db821-668a-47a5-962a-b784630520fc
  resourceVersion: "27392879"
  selfLink: /api/v1/namespaces/jx/pods/jx-preview-gc-jobs-1605099600-pxf66
  uid: 3ca325ae-2e5f-4341-bbce-f39d5d3c3bd3
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - jx gitops git setup --namespace jx --secret tekton-git && jx preview gc
    image: gcr.io/jenkinsxio/jx-cli:latest
    imagePullPolicy: IfNotPresent
    name: jx-preview-gc-jobs
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: jx-preview-gc-jobs-token-hvrbq
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-jstrachan-tekton-default-pool-154aeb80-pmxj
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: jx-preview-gc-jobs
  serviceAccountName: jx-preview-gc-jobs
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: jx-preview-gc-jobs-token-hvrbq
    secret:
      defaultMode: 420
      secretName: jx-preview-gc-jobs-token-hvrbq
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:00:08Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:00:08Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:00:08Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:00:08Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://acff5e65385bad6413dfbe51132772a3a6e124102df814043cd88838d154b3b3
    image: gcr.io/jenkinsxio/jx-cli:latest
    imageID: docker-pullable://gcr.io/jenkinsxio/jx-cli@sha256:fcd9bde5e3162d26e196b2cad77d76611a23a38207e4dc39e691b795c6815a7a
    lastState: {}
    name: jx-preview-gc-jobs
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://acff5e65385bad6413dfbe51132772a3a6e124102df814043cd88838d154b3b3
        exitCode: 0
        finishedAt: "2020-11-11T13:00:09Z"
        reason: Completed
        startedAt: "2020-11-11T13:00:09Z"
  hostIP: 10.128.0.11
  phase: Succeeded
  podIP: 10.8.7.103
  podIPs:
  - ip: 10.8.7.103
  qosClass: BestEffort
  startTime: "2020-11-11T13:00:08Z"
