apiVersion: v1
kind: Pod
metadata:
  annotations:
    comcast.github.io/check-name: jx-webhook
  creationTimestamp: "2020-11-11T13:54:18Z"
  labels:
    app: kuberhealthy-check
    kuberhealthy-check-name: jx-webhook
    kuberhealthy-run-id: e3a83422-0870-4c43-9d91-b5fc56f3ee45
  name: jx-webhook-1605102852
  namespace: jx
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: kuberhealthy-5c46966647-6db64
    uid: d98a024b-7504-4cdd-a3bb-c70c6128d8fb
  resourceVersion: "27428453"
  selfLink: /api/v1/namespaces/jx/pods/jx-webhook-1605102852
  uid: e24a0fa1-5e1a-4bd8-a2b9-92149e2dca5d
spec:
  containers:
  - env:
    - name: KH_REPORTING_URL
      value: http://kuberhealthy.kuberhealthy.svc.cluster.local/externalCheckStatus
    - name: KH_RUN_UUID
      value: e3a83422-0870-4c43-9d91-b5fc56f3ee45
    - name: KH_CHECK_RUN_DEADLINE
      value: "1605102972"
    - name: KH_POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: gcr.io/jenkinsxio/jx-webhooks:0.0.32
    imagePullPolicy: IfNotPresent
    name: jx-webhook
    resources:
      limits:
        cpu: 40m
      requests:
        cpu: 25m
        memory: 15Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: jx-webhook-sa-token-mt4b7
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-jstrachan-tekton-default-pool-154aeb80-pmxj
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: jx-webhook-sa
  serviceAccountName: jx-webhook-sa
  terminationGracePeriodSeconds: 60
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: jx-webhook-sa-token-mt4b7
    secret:
      defaultMode: 420
      secretName: jx-webhook-sa-token-mt4b7
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:54:18Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:54:23Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:54:23Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:54:18Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://65d27d42def83c0e934f00d3a96c142f5716edff64b280f14386cee6c2db9a63
    image: gcr.io/jenkinsxio/jx-webhooks:0.0.32
    imageID: docker-pullable://gcr.io/jenkinsxio/jx-webhooks@sha256:02b8be926e299e08202e933b90775428868c1adf5a30692c0d78e895039fc954
    lastState: {}
    name: jx-webhook
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://65d27d42def83c0e934f00d3a96c142f5716edff64b280f14386cee6c2db9a63
        exitCode: 0
        finishedAt: "2020-11-11T13:54:23Z"
        reason: Completed
        startedAt: "2020-11-11T13:54:21Z"
  hostIP: 10.128.0.11
  phase: Succeeded
  podIP: 10.8.7.11
  podIPs:
  - ip: 10.8.7.11
  qosClass: Burstable
  startTime: "2020-11-11T13:54:18Z"
