apiVersion: v1
kind: Pod
metadata:
  annotations:
    ad.datadoghq.com/keeper.logs: '[{"source":"lighthouse","service":"keeper"}]'
    wave.pusher.com/config-hash: d2b9232b24905e8c38452f792e043ec3970a5a4c120815b640f115a7352f407a
  creationTimestamp: "2020-11-11T13:20:19Z"
  generateName: lighthouse-keeper-6c7b89b4c5-
  labels:
    app: lighthouse-keeper
    draft: draft-app
    pod-template-hash: 6c7b89b4c5
  name: lighthouse-keeper-6c7b89b4c5-gsswn
  namespace: jx
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: lighthouse-keeper-6c7b89b4c5
    uid: 2a96ef60-cd05-4283-a8ce-099849b2cd2f
  resourceVersion: "27409212"
  selfLink: /api/v1/namespaces/jx/pods/lighthouse-keeper-6c7b89b4c5-gsswn
  uid: 13ba5718-85f3-4502-8f48-74fa1fed483f
spec:
  containers:
  - args:
    - --namespace=jx
    env:
    - name: GIT_KIND
      value: github
    - name: GIT_SERVER
      value: https://github.com
    - name: GIT_USER
    - name: GIT_TOKEN
      valueFrom:
        secretKeyRef:
          key: oauth
          name: lighthouse-oauth-token
    - name: JX_LOG_FORMAT
      value: json
    - name: LOGRUS_FORMAT
      value: json
    - name: LIGHTHOUSE_KEEPER_STATUS_CONTEXT_LABEL
      value: Lighthouse Merge Status
    image: gcr.io/jenkinsxio/lighthouse-keeper:0.0.874
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http
        scheme: HTTP
      initialDelaySeconds: 120
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: lighthouse-keeper
    ports:
    - containerPort: 8888
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 400m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: lighthouse-keeper-token-5dr6q
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-jstrachan-tekton-default-pool-154aeb80-n21q
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: lighthouse-keeper
  serviceAccountName: lighthouse-keeper
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: lighthouse-keeper-token-5dr6q
    secret:
      defaultMode: 420
      secretName: lighthouse-keeper-token-5dr6q
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:20:19Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:21:30Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:21:30Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-11T13:20:19Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://c7678c333991ac19ad3edae3cb0097eeb333ee8b9aea7a5963df58d7e3efb899
    image: gcr.io/jenkinsxio/lighthouse-keeper:0.0.874
    imageID: docker-pullable://gcr.io/jenkinsxio/lighthouse-keeper@sha256:42f73209128ae567a9515c45be6ca51c663d5acac843ea44b26380b4c13562e8
    lastState: {}
    name: lighthouse-keeper
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-11-11T13:20:22Z"
  hostIP: 10.128.0.5
  phase: Running
  podIP: 10.8.5.213
  podIPs:
  - ip: 10.8.5.213
  qosClass: Burstable
  startTime: "2020-11-11T13:20:19Z"
