# Source: nodey536/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-12-01T05:59:04Z"
  deletionTimestamp: null
  name: 'nodey536-1.0.12'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: added variables
      sha: d2efb474471e03fd75387c6c4829c8ce622d7847
    - author:
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        fix: better changelog
      sha: 8b126ba8df0c798c5f8aef987afa317c5bf7c630
  gitHttpUrl: https://github.com/jstrachan/nodey536
  gitOwner: jstrachan
  gitRepository: nodey536
  name: 'nodey536'
  releaseNotesURL: https://github.com/jstrachan/nodey536/releases/tag/v1.0.12
  version: v1.0.12
status: {}
