# Source: nodey536/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-12-01T06:03:23Z"
  deletionTimestamp: null
  name: 'nodey536-1.0.13'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: added variables
      sha: c95677b7da51d23dd2abe46ebece84ebbf187fd2
    - author:
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        fix: do changelog after tag
      sha: 75ec4c476805eb38cfc66b1e8445a11520e5179b
  gitHttpUrl: https://github.com/jstrachan/nodey536
  gitOwner: jstrachan
  gitRepository: nodey536
  name: 'nodey536'
  releaseNotesURL: https://github.com/jstrachan/nodey536/releases/tag/v1.0.13
  version: v1.0.13
status: {}
