# Source: nodey536/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-11-05T10:07:34Z"
  deletionTimestamp: null
  name: 'nodey536-1.0.3'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: jenkins-x-bot
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      branch: master
      committer:
        accountReference:
          - id: jenkins-x-bot
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      message: |
        release 1.0.3
      sha: 169310fa8007ab7ebd20d0f18ad95f3af8f80ee5
    - author:
        accountReference:
          - id: jenkins-x-bot
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      branch: master
      committer:
        accountReference:
          - id: jenkins-x-bot
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: jstrachan
      message: |
        release 1.0.3
      sha: 0041427a9f43774310a3e7667ca117b3b140c279
    - author:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        accountReference:
          - id: james-strachan-0
            provider: jenkins.io/git-github-userid
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        fix: change title
      sha: 090777c8c4730c4cd5864199e8f698507f572eb2
  gitCloneUrl: https://github.com/jstrachan/nodey536.git
  gitHttpUrl: https://github.com/jstrachan/nodey536
  gitOwner: jstrachan
  gitRepository: nodey536
  name: 'nodey536'
  releaseNotesURL: https://github.com/jstrachan/nodey536/releases/tag/v1.0.3
  version: v1.0.3
status: {}
