# Source: nodey536/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-12-01T05:46:57Z"
  deletionTimestamp: null
  name: 'nodey536-1.0.11'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: added variables
      sha: 34c2053d2fce0f09ff095038777452d37047442e
    - author:
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        fix: better changelog
      sha: fe6bcae9c770a4b09c87f507f9dcf41152325e99
  gitHttpUrl: https://github.com/jstrachan/nodey536
  gitOwner: jstrachan
  gitRepository: nodey536
  name: 'nodey536'
  releaseNotesURL: https://github.com/jstrachan/nodey536/releases/tag/v1.0.11
  version: v1.0.11
status: {}
