# Source: nodey536/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-12-02T08:37:37Z"
  deletionTimestamp: null
  name: 'nodey536-1.0.16'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: added variables
      sha: fe81b2dacccb6468aba2815974a3404daccd2582
    - author:
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        email: noreply@github.com
        name: GitHub
      message: Update index.html
      sha: 88d81c55f4576c247d8b12e9cbd8051512290511
  gitHttpUrl: https://github.com/jstrachan/nodey536
  gitOwner: jstrachan
  gitRepository: nodey536
  name: 'nodey536'
  releaseNotesURL: https://github.com/jstrachan/nodey536/releases/tag/v1.0.16
  version: v1.0.16
status: {}
