# Source: lighthouse/templates/foghorn-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighthouse-foghorn
  labels:
    draft: draft-app
    chart: "lighthouse-0.0.850"
    app: lighthouse-foghorn
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
  annotations:
    wave.pusher.com/update-on-config-change: 'true'
    jenkins-x.io/hash: '1f571c0d0ee1e73af3b9b76bdcb31264551ed3741a5b6d62533d8da5fe848c9b'
spec:
  replicas: 1
  selector:
    matchLabels:
      draft: draft-app
      app: lighthouse-foghorn
  template:
    metadata:
      labels:
        draft: draft-app
        app: lighthouse-foghorn
    spec:
      serviceAccountName: lighthouse-foghorn
      containers:
        - name: lighthouse-foghorn
          image: gcr.io/jenkinsxio/lighthouse-foghorn:0.0.850
          imagePullPolicy: IfNotPresent
          args:
            - "--namespace=jx"
          env:
            - name: "GIT_KIND"
              value: "github"
            - name: "GIT_SERVER"
              value: "https://github.com"
            - name: "GIT_USER"
              value: jstrachan
            - name: "GIT_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: lighthouse-oauth-token
                  key: oauth
            - name: "JX_LOG_FORMAT"
              value: "json"
            - name: "LOGRUS_FORMAT"
              value: "json"
            - name: JX_DEFAULT_IMAGE
              value: "gcr.io/jenkinsxio/builder-maven:2.1.142-761"
            - name: LIGHTHOUSE_DASHBOARD_TEMPLATE
              value: "namespaces/{{ .Namespace }}/pipelineruns/{{ .PipelineRun }}"
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 80m
              memory: 128Mi
      terminationGracePeriodSeconds: 180
